/*
 * Copyright (c) 2017, Adam <Adam@sigterm.info>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package com.theplug.kotori.kotoritest.kotoriutils.rlapi;

/**
 * Represents a group-child Widget relationship.
 * <p>
 * For getting a specific widget from the client, see net.runelite.api.Client#getWidget(WidgetInfo).
 */
public enum WidgetInfoPlus
{
	FAIRY_RING_LEFT_ORB_CLOCKWISE(WidgetIDPlus.FAIRY_RING_GROUP_ID, WidgetIDPlus.FairyRing.LEFT_ORB_CLOCKWISE),
	FAIRY_RING_LEFT_ORB_COUNTER_CLOCKWISE(WidgetIDPlus.FAIRY_RING_GROUP_ID, WidgetIDPlus.FairyRing.LEFT_ORB_COUNTER_CLOCKWISE),
	FAIRY_RING_MIDDLE_ORB_CLOCKWISE(WidgetIDPlus.FAIRY_RING_GROUP_ID, WidgetIDPlus.FairyRing.MIDDLE_ORB_CLOCKWISE),
	FAIRY_RING_MIDDLE_ORB_COUNTER_CLOCKWISE(WidgetIDPlus.FAIRY_RING_GROUP_ID, WidgetIDPlus.FairyRing.MIDDLE_ORB_COUNTER_CLOCKWISE),
	FAIRY_RING_RIGHT_ORB_CLOCKWISE(WidgetIDPlus.FAIRY_RING_GROUP_ID, WidgetIDPlus.FairyRing.RIGHT_ORB_CLOCKWISE),
	FAIRY_RING_RIGHT_ORB_COUNTER_CLOCKWISE(WidgetIDPlus.FAIRY_RING_GROUP_ID, WidgetIDPlus.FairyRing.RIGHT_ORB_COUNTER_CLOCKWISE),
	
	FAIRY_RING_TELEPORT_BUTTON(WidgetIDPlus.FAIRY_RING_GROUP_ID, WidgetIDPlus.FairyRing.TELEPORT_BUTTON),
	
	WORLD_SWITCHER_BUTTON(WidgetIDPlus.LOGOUT_PANEL_ID, WidgetIDPlus.LogoutPanel.WORLD_SWITCHER_BUTTON),
	LOGOUT_BUTTON(WidgetIDPlus.LOGOUT_PANEL_ID, WidgetIDPlus.LogoutPanel.LOGOUT_BUTTON),
	
	INVENTORY(WidgetIDPlus.INVENTORY_GROUP_ID, 0),
	FRIENDS_LIST(WidgetIDPlus.FRIENDS_LIST_GROUP_ID, 0),
	IGNORE_LIST(WidgetIDPlus.IGNORE_LIST_GROUP_ID, 0),
	FRIENDS_CHAT(WidgetIDPlus.FRIENDS_CHAT_GROUP_ID, 0),
	RAIDING_PARTY(WidgetIDPlus.RAIDING_PARTY_GROUP_ID, 0),
	
	WORLD_MAP_VIEW(WidgetIDPlus.WORLD_MAP_GROUP_ID, WidgetIDPlus.WorldMap.MAPVIEW),
	WORLD_MAP_OVERVIEW_MAP(WidgetIDPlus.WORLD_MAP_GROUP_ID, WidgetIDPlus.WorldMap.OVERVIEW_MAP),
	WORLD_MAP_BOTTOM_BAR(WidgetIDPlus.WORLD_MAP_GROUP_ID, WidgetIDPlus.WorldMap.BOTTOM_BAR),
	WORLD_MAP_SEARCH(WidgetIDPlus.WORLD_MAP_GROUP_ID, WidgetIDPlus.WorldMap.SEARCH),
	WORLD_MAP_SURFACE_SELECTOR(WidgetIDPlus.WORLD_MAP_GROUP_ID, WidgetIDPlus.WorldMap.SURFACE_SELECTOR),
	WORLD_MAP_TOOLTIP(WidgetIDPlus.WORLD_MAP_GROUP_ID, WidgetIDPlus.WorldMap.TOOLTIP),
	
	CLUE_SCROLL_TEXT(WidgetIDPlus.CLUE_SCROLL_GROUP_ID, WidgetIDPlus.Cluescroll.CLUE_TEXT),
	CLUE_SCROLL_REWARD_ITEM_CONTAINER(WidgetIDPlus.CLUE_SCROLL_REWARD_GROUP_ID, WidgetIDPlus.Cluescroll.CLUE_SCROLL_ITEM_CONTAINER),
	
	EQUIPMENT(WidgetIDPlus.EQUIPMENT_GROUP_ID, 0),
	EQUIPMENT_INVENTORY_ITEMS_CONTAINER(WidgetIDPlus.EQUIPMENT_INVENTORY_GROUP_ID, WidgetIDPlus.Equipment.INVENTORY_ITEM_CONTAINER),
	
	EMOTE_WINDOW(WidgetIDPlus.EMOTES_GROUP_ID, WidgetIDPlus.Emotes.EMOTE_WINDOW),
	EMOTE_SCROLL_CONTAINER(WidgetIDPlus.EMOTES_GROUP_ID, WidgetIDPlus.Emotes.EMOTE_SCROLL_CONTAINER),
	EMOTE_CONTAINER(WidgetIDPlus.EMOTES_GROUP_ID, WidgetIDPlus.Emotes.EMOTE_CONTAINER),
	EMOTE_SCROLLBAR(WidgetIDPlus.EMOTES_GROUP_ID, WidgetIDPlus.Emotes.EMOTE_SCROLLBAR),
	
	MUSIC_WINDOW(WidgetIDPlus.MUSIC_GROUP_ID, WidgetIDPlus.Music.CONTAINER),
	MUSIC_TRACK_LIST(WidgetIDPlus.MUSIC_GROUP_ID, WidgetIDPlus.Music.LIST),
	MUSIC_TRACK_SCROLL_CONTAINER(WidgetIDPlus.MUSIC_GROUP_ID, WidgetIDPlus.Music.SCROLL_CONTAINER),
	MUSIC_TRACK_SCROLLBAR(WidgetIDPlus.MUSIC_GROUP_ID, WidgetIDPlus.Music.SCROLLBAR),
	
	DIARY_QUEST_WIDGET_TITLE(WidgetIDPlus.DIARY_QUEST_GROUP_ID, WidgetIDPlus.Diary.DIARY_TITLE),
	DIARY_QUEST_WIDGET_TEXT(WidgetIDPlus.DIARY_QUEST_GROUP_ID, WidgetIDPlus.Diary.DIARY_TEXT),
	
	ACHIEVEMENT_DIARY_SCROLL_TITLE(WidgetIDPlus.ACHIEVEMENT_DIARY_SCROLL_GROUP_ID, WidgetIDPlus.AchievementDiaryScroll.TITLE),
	ACHIEVEMENT_DIARY_SCROLL_TEXT(WidgetIDPlus.ACHIEVEMENT_DIARY_SCROLL_GROUP_ID, WidgetIDPlus.AchievementDiaryScroll.TEXT),
	
	PEST_CONTROL_BOAT_INFO(WidgetIDPlus.PEST_CONTROL_BOAT_GROUP_ID, 2),
	PEST_CONTROL_KNIGHT_INFO_CONTAINER(WidgetIDPlus.PEST_CONTROL_GROUP_ID, WidgetIDPlus.PestControl.KNIGHT_INFO_CONTAINER),
	PEST_CONTROL_ACTIVITY_SHIELD_INFO_CONTAINER(WidgetIDPlus.PEST_CONTROL_GROUP_ID, WidgetIDPlus.PestControl.ACTIVITY_SHIELD_CONTAINER),
	PEST_CONTROL_PURPLE_SHIELD(WidgetIDPlus.PEST_CONTROL_GROUP_ID, WidgetIDPlus.PestControl.PURPLE_SHIELD),
	PEST_CONTROL_BLUE_SHIELD(WidgetIDPlus.PEST_CONTROL_GROUP_ID, WidgetIDPlus.PestControl.BLUE_SHIELD),
	PEST_CONTROL_YELLOW_SHIELD(WidgetIDPlus.PEST_CONTROL_GROUP_ID, WidgetIDPlus.PestControl.YELLOW_SHIELD),
	PEST_CONTROL_RED_SHIELD(WidgetIDPlus.PEST_CONTROL_GROUP_ID, WidgetIDPlus.PestControl.RED_SHIELD),
	PEST_CONTROL_PURPLE_HEALTH(WidgetIDPlus.PEST_CONTROL_GROUP_ID, WidgetIDPlus.PestControl.PURPLE_HEALTH),
	PEST_CONTROL_BLUE_HEALTH(WidgetIDPlus.PEST_CONTROL_GROUP_ID, WidgetIDPlus.PestControl.BLUE_HEALTH),
	PEST_CONTROL_YELLOW_HEALTH(WidgetIDPlus.PEST_CONTROL_GROUP_ID, WidgetIDPlus.PestControl.YELLOW_HEALTH),
	PEST_CONTROL_RED_HEALTH(WidgetIDPlus.PEST_CONTROL_GROUP_ID, WidgetIDPlus.PestControl.RED_HEALTH),
	PEST_CONTROL_PURPLE_ICON(WidgetIDPlus.PEST_CONTROL_GROUP_ID, WidgetIDPlus.PestControl.PURPLE_ICON),
	PEST_CONTROL_BLUE_ICON(WidgetIDPlus.PEST_CONTROL_GROUP_ID, WidgetIDPlus.PestControl.BLUE_ICON),
	PEST_CONTROL_YELLOW_ICON(WidgetIDPlus.PEST_CONTROL_GROUP_ID, WidgetIDPlus.PestControl.YELLOW_ICON),
	PEST_CONTROL_RED_ICON(WidgetIDPlus.PEST_CONTROL_GROUP_ID, WidgetIDPlus.PestControl.RED_ICON),
	PEST_CONTROL_ACTIVITY_BAR(WidgetIDPlus.PEST_CONTROL_GROUP_ID, WidgetIDPlus.PestControl.ACTIVITY_BAR),
	PEST_CONTROL_ACTIVITY_PROGRESS(WidgetIDPlus.PEST_CONTROL_GROUP_ID, WidgetIDPlus.PestControl.ACTIVITY_PROGRESS),
	
	VOLCANIC_MINE_TIME_LEFT(WidgetIDPlus.VOLCANIC_MINE_GROUP_ID, WidgetIDPlus.VolcanicMine.TIME_LEFT),
	VOLCANIC_MINE_POINTS(WidgetIDPlus.VOLCANIC_MINE_GROUP_ID, WidgetIDPlus.VolcanicMine.POINTS),
	VOLCANIC_MINE_STABILITY(WidgetIDPlus.VOLCANIC_MINE_GROUP_ID, WidgetIDPlus.VolcanicMine.STABILITY),
	VOLCANIC_MINE_PLAYER_COUNT(WidgetIDPlus.VOLCANIC_MINE_GROUP_ID, WidgetIDPlus.VolcanicMine.PLAYER_COUNT),
	VOLCANIC_MINE_VENTS_INFOBOX_GROUP(WidgetIDPlus.VOLCANIC_MINE_GROUP_ID, WidgetIDPlus.VolcanicMine.VENTS_INFOBOX_CONTAINER),
	VOLCANIC_MINE_STABILITY_INFOBOX_GROUP(WidgetIDPlus.VOLCANIC_MINE_GROUP_ID, WidgetIDPlus.VolcanicMine.STABILITY_INFOBOX_CONTAINER),
	VOLCANIC_MINE_VENT_A_PERCENTAGE(WidgetIDPlus.VOLCANIC_MINE_GROUP_ID, WidgetIDPlus.VolcanicMine.VENT_A_PERCENTAGE),
	VOLCANIC_MINE_VENT_B_PERCENTAGE(WidgetIDPlus.VOLCANIC_MINE_GROUP_ID, WidgetIDPlus.VolcanicMine.VENT_B_PERCENTAGE),
	VOLCANIC_MINE_VENT_C_PERCENTAGE(WidgetIDPlus.VOLCANIC_MINE_GROUP_ID, WidgetIDPlus.VolcanicMine.VENT_C_PERCENTAGE),
	VOLCANIC_MINE_VENT_A_STATUS(WidgetIDPlus.VOLCANIC_MINE_GROUP_ID, WidgetIDPlus.VolcanicMine.VENT_A_STATUS),
	VOLCANIC_MINE_VENT_B_STATUS(WidgetIDPlus.VOLCANIC_MINE_GROUP_ID, WidgetIDPlus.VolcanicMine.VENT_B_STATUS),
	VOLCANIC_MINE_VENT_C_STATUS(WidgetIDPlus.VOLCANIC_MINE_GROUP_ID, WidgetIDPlus.VolcanicMine.VENT_C_STATUS),
	
	FRIEND_CHAT_TITLE(WidgetIDPlus.FRIENDS_LIST_GROUP_ID, WidgetIDPlus.FriendList.TITLE),
	FRIEND_LIST_FULL_CONTAINER(WidgetIDPlus.FRIENDS_LIST_GROUP_ID, WidgetIDPlus.FriendList.FULL_CONTAINER),
	FRIEND_LIST_SORT_BY_NAME_BUTTON(WidgetIDPlus.FRIENDS_LIST_GROUP_ID, WidgetIDPlus.FriendList.SORT_BY_NAME_BUTTON),
	FRIEND_LIST_SORT_BY_LAST_WORLD_CHANGE_BUTTON(WidgetIDPlus.FRIENDS_LIST_GROUP_ID, WidgetIDPlus.FriendList.SORT_BY_LAST_WORLD_CHANGE_BUTTON),
	FRIEND_LIST_SORT_BY_WORLD_BUTTON(WidgetIDPlus.FRIENDS_LIST_GROUP_ID, WidgetIDPlus.FriendList.SORT_BY_WORLD_BUTTON),
	FRIEND_LIST_LEGACY_SORT_BUTTON(WidgetIDPlus.FRIENDS_LIST_GROUP_ID, WidgetIDPlus.FriendList.LEGACY_SORT_BUTTON),
	FRIEND_LIST_NAMES_CONTAINER(WidgetIDPlus.FRIENDS_LIST_GROUP_ID, WidgetIDPlus.FriendList.NAMES_CONTAINER),
	FRIEND_LIST_SCROLL_BAR(WidgetIDPlus.FRIENDS_LIST_GROUP_ID, WidgetIDPlus.FriendList.SCROLL_BAR),
	FRIEND_LIST_LOADING_TEXT(WidgetIDPlus.FRIENDS_LIST_GROUP_ID, WidgetIDPlus.FriendList.LOADING_TEXT),
	FRIEND_LIST_PREVIOUS_NAME_HOLDER(WidgetIDPlus.FRIENDS_LIST_GROUP_ID, WidgetIDPlus.FriendList.PREVIOUS_NAME_HOLDER),
	
	IGNORE_TITLE(WidgetIDPlus.IGNORE_LIST_GROUP_ID, WidgetIDPlus.IgnoreList.TITLE),
	IGNORE_FULL_CONTAINER(WidgetIDPlus.IGNORE_LIST_GROUP_ID, WidgetIDPlus.IgnoreList.FULL_CONTAINER),
	IGNORE_SORT_BY_NAME_BUTTON(WidgetIDPlus.IGNORE_LIST_GROUP_ID, WidgetIDPlus.IgnoreList.SORT_BY_NAME_BUTTON),
	IGNORE_LEGACY_SORT_BUTTON(WidgetIDPlus.IGNORE_LIST_GROUP_ID, WidgetIDPlus.IgnoreList.LEGACY_SORT_BUTTON),
	IGNORE_NAMES_CONTAINER(WidgetIDPlus.IGNORE_LIST_GROUP_ID, WidgetIDPlus.IgnoreList.NAMES_CONTAINER),
	IGNORE_SCROLL_BAR(WidgetIDPlus.IGNORE_LIST_GROUP_ID, WidgetIDPlus.IgnoreList.SCROLL_BAR),
	IGNORE_LOADING_TEXT(WidgetIDPlus.IGNORE_LIST_GROUP_ID, WidgetIDPlus.IgnoreList.LOADING_TEXT),
	IGNORE_PREVIOUS_NAME_HOLDER(WidgetIDPlus.IGNORE_LIST_GROUP_ID, WidgetIDPlus.IgnoreList.PREVIOUS_NAME_HOLDER),
	
	EXPLORERS_RING_ALCH_INVENTORY(WidgetIDPlus.EXPLORERS_RING_ALCH_GROUP_ID, WidgetIDPlus.ExplorersRing.INVENTORY),
	
	FRIENDS_CHAT_ROOT(WidgetIDPlus.FRIENDS_CHAT_GROUP_ID, WidgetIDPlus.FriendsChat.ROOT),
	FRIENDS_CHAT_TITLE(WidgetIDPlus.FRIENDS_CHAT_GROUP_ID, WidgetIDPlus.FriendsChat.TITLE),
	FRIENDS_CHAT_OWNER(WidgetIDPlus.FRIENDS_CHAT_GROUP_ID, WidgetIDPlus.FriendsChat.OWNER),
	FRIENDS_CHAT_LIST(WidgetIDPlus.FRIENDS_CHAT_GROUP_ID, WidgetIDPlus.FriendsChat.LIST),
	
	BANK_CONTAINER(WidgetIDPlus.BANK_GROUP_ID, WidgetIDPlus.Bank.BANK_CONTAINER),
	BANK_SEARCH_BUTTON_BACKGROUND(WidgetIDPlus.BANK_GROUP_ID, WidgetIDPlus.Bank.SEARCH_BUTTON_BACKGROUND),
	BANK_ITEM_CONTAINER(WidgetIDPlus.BANK_GROUP_ID, WidgetIDPlus.Bank.ITEM_CONTAINER),
	BANK_INVENTORY_ITEMS_CONTAINER(WidgetIDPlus.BANK_INVENTORY_GROUP_ID, WidgetIDPlus.Bank.INVENTORY_ITEM_CONTAINER),
	BANK_TITLE_BAR(WidgetIDPlus.BANK_GROUP_ID, WidgetIDPlus.Bank.BANK_TITLE_BAR),
	BANK_INCINERATOR(WidgetIDPlus.BANK_GROUP_ID, WidgetIDPlus.Bank.INCINERATOR),
	BANK_INCINERATOR_CONFIRM(WidgetIDPlus.BANK_GROUP_ID, WidgetIDPlus.Bank.INCINERATOR_CONFIRM),
	BANK_CONTENT_CONTAINER(WidgetIDPlus.BANK_GROUP_ID, WidgetIDPlus.Bank.CONTENT_CONTAINER),
	BANK_DEPOSIT_EQUIPMENT(WidgetIDPlus.BANK_GROUP_ID, WidgetIDPlus.Bank.DEPOSIT_EQUIPMENT),
	BANK_DEPOSIT_INVENTORY(WidgetIDPlus.BANK_GROUP_ID, WidgetIDPlus.Bank.DEPOSIT_INVENTORY),
	BANK_TAB_CONTAINER(WidgetIDPlus.BANK_GROUP_ID, WidgetIDPlus.Bank.TAB_CONTAINER),
	BANK_EQUIPMENT_CONTAINER(WidgetIDPlus.BANK_GROUP_ID, WidgetIDPlus.Bank.EQUIPMENT_CONTENT_CONTAINER),
	BANK_EQUIPMENT_BUTTON(WidgetIDPlus.BANK_GROUP_ID, WidgetIDPlus.Bank.EQUIPMENT_BUTTON),
	BANK_ITEM_COUNT_TOP(WidgetIDPlus.BANK_GROUP_ID, WidgetIDPlus.Bank.ITEM_COUNT_TOP),
	BANK_ITEM_COUNT_BAR(WidgetIDPlus.BANK_GROUP_ID, WidgetIDPlus.Bank.ITEM_COUNT_BAR),
	BANK_ITEM_COUNT_BOTTOM(WidgetIDPlus.BANK_GROUP_ID, WidgetIDPlus.Bank.ITEM_COUNT_BOTTOM),
	BANK_GROUP_STORAGE_BUTTON(WidgetIDPlus.BANK_GROUP_ID, WidgetIDPlus.Bank.GROUP_STORAGE_BUTTON),
	BANK_SCROLLBAR(WidgetIDPlus.BANK_GROUP_ID, WidgetIDPlus.Bank.SCROLLBAR),
	BANK_PIN_CONTAINER(WidgetIDPlus.BANK_PIN_GROUP_ID, WidgetIDPlus.BankPin.CONTAINER),
	BANK_SETTINGS_BUTTON(WidgetIDPlus.BANK_GROUP_ID, WidgetIDPlus.Bank.SETTINGS_BUTTON),
	BANK_TUTORIAL_BUTTON(WidgetIDPlus.BANK_GROUP_ID, WidgetIDPlus.Bank.TUTORIAL_BUTTON),
	
	GROUP_STORAGE_UI(WidgetIDPlus.GROUP_STORAGE_GROUP_ID, WidgetIDPlus.GroupStorage.UI),
	GROUP_STORAGE_ITEM_CONTAINER(WidgetIDPlus.GROUP_STORAGE_GROUP_ID, WidgetIDPlus.GroupStorage.ITEM_CONTAINER),
	
	GRAND_EXCHANGE_WINDOW_CONTAINER(WidgetIDPlus.GRAND_EXCHANGE_GROUP_ID, WidgetIDPlus.GrandExchange.WINDOW_CONTAINER),
	GRAND_EXCHANGE_OFFER_CONTAINER(WidgetIDPlus.GRAND_EXCHANGE_GROUP_ID, WidgetIDPlus.GrandExchange.OFFER_CONTAINER),
	GRAND_EXCHANGE_OFFER_TEXT(WidgetIDPlus.GRAND_EXCHANGE_GROUP_ID, WidgetIDPlus.GrandExchange.OFFER_DESCRIPTION),
	
	GRAND_EXCHANGE_INVENTORY_ITEMS_CONTAINER(WidgetIDPlus.GRAND_EXCHANGE_INVENTORY_GROUP_ID, WidgetIDPlus.GrandExchangeInventory.INVENTORY_ITEM_CONTAINER),
	
	DEPOSIT_BOX_INVENTORY_ITEMS_CONTAINER(WidgetIDPlus.DEPOSIT_BOX_GROUP_ID, WidgetIDPlus.DepositBox.INVENTORY_ITEM_CONTAINER),
	
	SHOP_INVENTORY_ITEMS_CONTAINER(WidgetIDPlus.SHOP_INVENTORY_GROUP_ID, WidgetIDPlus.Shop.INVENTORY_ITEM_CONTAINER),
	
	SMITHING_INVENTORY_ITEMS_CONTAINER(WidgetIDPlus.SMITHING_GROUP_ID, WidgetIDPlus.Smithing.INVENTORY_ITEM_CONTAINER),
	
	GUIDE_PRICES_ITEMS_CONTAINER(WidgetIDPlus.GUIDE_PRICES_GROUP_ID, WidgetIDPlus.GuidePrices.ITEM_CONTAINER),
	GUIDE_PRICES_INVENTORY_ITEMS_CONTAINER(WidgetIDPlus.GUIDE_PRICES_INVENTORY_GROUP_ID, WidgetIDPlus.GuidePrices.INVENTORY_ITEM_CONTAINER),
	
	RUNE_POUCH_ITEM_CONTAINER(WidgetIDPlus.RUNE_POUCH_GROUP_ID, 0),
	
	MINIMAP_ORBS(WidgetIDPlus.MINIMAP_GROUP_ID, 0),
	MINIMAP_XP_ORB(WidgetIDPlus.MINIMAP_GROUP_ID, WidgetIDPlus.Minimap.XP_ORB),
	MINIMAP_PRAYER_ORB(WidgetIDPlus.MINIMAP_GROUP_ID, WidgetIDPlus.Minimap.PRAYER_ORB),
	MINIMAP_QUICK_PRAYER_ORB(WidgetIDPlus.MINIMAP_GROUP_ID, WidgetIDPlus.Minimap.QUICK_PRAYER_ORB),
	MINIMAP_PRAYER_ORB_TEXT(WidgetIDPlus.MINIMAP_GROUP_ID, WidgetIDPlus.Minimap.PRAYER_ORB_TEXT),
	MINIMAP_RUN_ORB(WidgetIDPlus.MINIMAP_GROUP_ID, WidgetIDPlus.Minimap.RUN_ORB),
	MINIMAP_TOGGLE_RUN_ORB(WidgetIDPlus.MINIMAP_GROUP_ID, WidgetIDPlus.Minimap.TOGGLE_RUN_ORB),
	MINIMAP_RUN_ORB_TEXT(WidgetIDPlus.MINIMAP_GROUP_ID, WidgetIDPlus.Minimap.RUN_ORB_TEXT),
	MINIMAP_HEALTH_ORB(WidgetIDPlus.MINIMAP_GROUP_ID, WidgetIDPlus.Minimap.HEALTH_ORB),
	MINIMAP_SPEC_ORB(WidgetIDPlus.MINIMAP_GROUP_ID, WidgetIDPlus.Minimap.SPEC_ORB),
	MINIMAP_SPEC_CLICKBOX(WidgetIDPlus.MINIMAP_GROUP_ID, WidgetIDPlus.Minimap.SPEC_CLICKBOX),
	MINIMAP_WORLDMAP_ORB(WidgetIDPlus.MINIMAP_GROUP_ID, WidgetIDPlus.Minimap.WORLDMAP_ORB),
	MINIMAP_WIKI_BANNER_PARENT(WidgetIDPlus.MINIMAP_GROUP_ID, WidgetIDPlus.Minimap.WIKI_BANNER_PARENT),
	MINIMAP_WIKI_BANNER(WidgetIDPlus.MINIMAP_GROUP_ID, WidgetIDPlus.Minimap.WIKI_BANNER),
	MINIMAP_WORLDMAP_OPTIONS(WidgetIDPlus.MINIMAP_GROUP_ID, WidgetIDPlus.Minimap.WORLDMAP_OPTIONS),
	
	LMS_INFO(WidgetIDPlus.LMS_GROUP_ID, WidgetIDPlus.Lms.INFO),
	LMS_KDA(WidgetIDPlus.LMS_INGAME_GROUP_ID, WidgetIDPlus.LmsKDA.INFO),
	
	LOGIN_CLICK_TO_PLAY_SCREEN(WidgetIDPlus.LOGIN_CLICK_TO_PLAY_GROUP_ID, 0),
	LOGIN_CLICK_TO_PLAY_SCREEN_MESSAGE_OF_THE_DAY(WidgetIDPlus.LOGIN_CLICK_TO_PLAY_GROUP_ID, WidgetIDPlus.LoginClickToPlayScreen.MESSAGE_OF_THE_DAY),
	
	FIXED_VIEWPORT(WidgetIDPlus.FIXED_VIEWPORT_GROUP_ID, WidgetIDPlus.FixedViewport.FIXED_VIEWPORT),
	FIXED_VIEWPORT_ROOT_INTERFACE_CONTAINER(WidgetIDPlus.FIXED_VIEWPORT_GROUP_ID, WidgetIDPlus.FixedViewport.ROOT_INTERFACE_CONTAINER),
	FIXED_VIEWPORT_BANK_CONTAINER(WidgetIDPlus.FIXED_VIEWPORT_GROUP_ID, WidgetIDPlus.FixedViewport.BANK_CONTAINER),
	FIXED_VIEWPORT_INTERFACE_CONTAINER(WidgetIDPlus.FIXED_VIEWPORT_GROUP_ID, WidgetIDPlus.FixedViewport.INTERFACE_CONTAINER),
	FIXED_VIEWPORT_INVENTORY_CONTAINER(WidgetIDPlus.FIXED_VIEWPORT_GROUP_ID, WidgetIDPlus.FixedViewport.INVENTORY_CONTAINER),
	FIXED_VIEWPORT_COMBAT_TAB(WidgetIDPlus.FIXED_VIEWPORT_GROUP_ID, WidgetIDPlus.FixedViewport.COMBAT_TAB),
	FIXED_VIEWPORT_STATS_TAB(WidgetIDPlus.FIXED_VIEWPORT_GROUP_ID, WidgetIDPlus.FixedViewport.STATS_TAB),
	FIXED_VIEWPORT_QUESTS_TAB(WidgetIDPlus.FIXED_VIEWPORT_GROUP_ID, WidgetIDPlus.FixedViewport.QUESTS_TAB),
	FIXED_VIEWPORT_INVENTORY_TAB(WidgetIDPlus.FIXED_VIEWPORT_GROUP_ID, WidgetIDPlus.FixedViewport.INVENTORY_TAB),
	FIXED_VIEWPORT_EQUIPMENT_TAB(WidgetIDPlus.FIXED_VIEWPORT_GROUP_ID, WidgetIDPlus.FixedViewport.EQUIPMENT_TAB),
	FIXED_VIEWPORT_PRAYER_TAB(WidgetIDPlus.FIXED_VIEWPORT_GROUP_ID, WidgetIDPlus.FixedViewport.PRAYER_TAB),
	FIXED_VIEWPORT_MAGIC_TAB(WidgetIDPlus.FIXED_VIEWPORT_GROUP_ID, WidgetIDPlus.FixedViewport.MAGIC_TAB),
	FIXED_VIEWPORT_FRIENDS_CHAT_TAB(WidgetIDPlus.FIXED_VIEWPORT_GROUP_ID, WidgetIDPlus.FixedViewport.FRIENDS_CHAT_TAB),
	FIXED_VIEWPORT_FRIENDS_TAB(WidgetIDPlus.FIXED_VIEWPORT_GROUP_ID, WidgetIDPlus.FixedViewport.FRIENDS_TAB),
	FIXED_VIEWPORT_IGNORES_TAB(WidgetIDPlus.FIXED_VIEWPORT_GROUP_ID, WidgetIDPlus.FixedViewport.IGNORES_TAB),
	FIXED_VIEWPORT_LOGOUT_TAB(WidgetIDPlus.FIXED_VIEWPORT_GROUP_ID, WidgetIDPlus.FixedViewport.LOGOUT_TAB),
	FIXED_VIEWPORT_OPTIONS_TAB(WidgetIDPlus.FIXED_VIEWPORT_GROUP_ID, WidgetIDPlus.FixedViewport.OPTIONS_TAB),
	FIXED_VIEWPORT_EMOTES_TAB(WidgetIDPlus.FIXED_VIEWPORT_GROUP_ID, WidgetIDPlus.FixedViewport.EMOTES_TAB),
	FIXED_VIEWPORT_MUSIC_TAB(WidgetIDPlus.FIXED_VIEWPORT_GROUP_ID, WidgetIDPlus.FixedViewport.MUSIC_TAB),
	FIXED_VIEWPORT_COMBAT_ICON(WidgetIDPlus.FIXED_VIEWPORT_GROUP_ID, WidgetIDPlus.FixedViewport.COMBAT_ICON),
	FIXED_VIEWPORT_STATS_ICON(WidgetIDPlus.FIXED_VIEWPORT_GROUP_ID, WidgetIDPlus.FixedViewport.STATS_ICON),
	FIXED_VIEWPORT_QUESTS_ICON(WidgetIDPlus.FIXED_VIEWPORT_GROUP_ID, WidgetIDPlus.FixedViewport.QUESTS_ICON),
	FIXED_VIEWPORT_INVENTORY_ICON(WidgetIDPlus.FIXED_VIEWPORT_GROUP_ID, WidgetIDPlus.FixedViewport.INVENTORY_ICON),
	FIXED_VIEWPORT_EQUIPMENT_ICON(WidgetIDPlus.FIXED_VIEWPORT_GROUP_ID, WidgetIDPlus.FixedViewport.EQUIPMENT_ICON),
	FIXED_VIEWPORT_PRAYER_ICON(WidgetIDPlus.FIXED_VIEWPORT_GROUP_ID, WidgetIDPlus.FixedViewport.PRAYER_ICON),
	FIXED_VIEWPORT_MAGIC_ICON(WidgetIDPlus.FIXED_VIEWPORT_GROUP_ID, WidgetIDPlus.FixedViewport.MAGIC_ICON),
	FIXED_VIEWPORT_FRIENDS_CHAT_ICON(WidgetIDPlus.FIXED_VIEWPORT_GROUP_ID, WidgetIDPlus.FixedViewport.FRIENDS_CHAT_ICON),
	FIXED_VIEWPORT_FRIENDS_ICON(WidgetIDPlus.FIXED_VIEWPORT_GROUP_ID, WidgetIDPlus.FixedViewport.FRIENDS_ICON),
	FIXED_VIEWPORT_IGNORES_ICON(WidgetIDPlus.FIXED_VIEWPORT_GROUP_ID, WidgetIDPlus.FixedViewport.IGNORES_ICON),
	FIXED_VIEWPORT_LOGOUT_ICON(WidgetIDPlus.FIXED_VIEWPORT_GROUP_ID, WidgetIDPlus.FixedViewport.LOGOUT_ICON),
	FIXED_VIEWPORT_OPTIONS_ICON(WidgetIDPlus.FIXED_VIEWPORT_GROUP_ID, WidgetIDPlus.FixedViewport.OPTIONS_ICON),
	FIXED_VIEWPORT_EMOTES_ICON(WidgetIDPlus.FIXED_VIEWPORT_GROUP_ID, WidgetIDPlus.FixedViewport.EMOTES_ICON),
	FIXED_VIEWPORT_MUSIC_ICON(WidgetIDPlus.FIXED_VIEWPORT_GROUP_ID, WidgetIDPlus.FixedViewport.MUSIC_ICON),
	FIXED_VIEWPORT_MINIMAP(WidgetIDPlus.FIXED_VIEWPORT_GROUP_ID, WidgetIDPlus.FixedViewport.MINIMAP),
	FIXED_VIEWPORT_MINIMAP_DRAW_AREA(WidgetIDPlus.FIXED_VIEWPORT_GROUP_ID, WidgetIDPlus.FixedViewport.MINIMAP_DRAW_AREA),
	
	RESIZABLE_MINIMAP_STONES_WIDGET(WidgetIDPlus.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDPlus.ResizableViewport.MINIMAP),
	RESIZABLE_MINIMAP_STONES_DRAW_AREA(WidgetIDPlus.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDPlus.ResizableViewport.MINIMAP_DRAW_AREA),
	RESIZABLE_MINIMAP_STONES_ORB_HOLDER(WidgetIDPlus.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDPlus.ResizableViewport.MINIMAP_ORB_HOLDER),
	RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX(WidgetIDPlus.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDPlus.ResizableViewport.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX),
	RESIZABLE_VIEWPORT_COMBAT_TAB(WidgetIDPlus.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDPlus.ResizableViewport.COMBAT_TAB),
	RESIZABLE_VIEWPORT_STATS_TAB(WidgetIDPlus.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDPlus.ResizableViewport.STATS_TAB),
	RESIZABLE_VIEWPORT_QUESTS_TAB(WidgetIDPlus.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDPlus.ResizableViewport.QUESTS_TAB),
	RESIZABLE_VIEWPORT_INVENTORY_TAB(WidgetIDPlus.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDPlus.ResizableViewport.INVENTORY_TAB),
	RESIZABLE_VIEWPORT_EQUIPMENT_TAB(WidgetIDPlus.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDPlus.ResizableViewport.EQUIPMENT_TAB),
	RESIZABLE_VIEWPORT_PRAYER_TAB(WidgetIDPlus.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDPlus.ResizableViewport.PRAYER_TAB),
	RESIZABLE_VIEWPORT_MAGIC_TAB(WidgetIDPlus.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDPlus.ResizableViewport.MAGIC_TAB),
	RESIZABLE_VIEWPORT_FRIENDS_CHAT_TAB(WidgetIDPlus.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDPlus.ResizableViewport.FRIENDS_CHAT_TAB),
	RESIZABLE_VIEWPORT_FRIENDS_TAB(WidgetIDPlus.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDPlus.ResizableViewport.FRIENDS_TAB),
	RESIZABLE_VIEWPORT_IGNORES_TAB(WidgetIDPlus.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDPlus.ResizableViewport.IGNORES_TAB),
	RESIZABLE_VIEWPORT_LOGOUT_TAB(WidgetIDPlus.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDPlus.ResizableViewport.LOGOUT_TAB),
	RESIZABLE_VIEWPORT_OPTIONS_TAB(WidgetIDPlus.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDPlus.ResizableViewport.OPTIONS_TAB),
	RESIZABLE_VIEWPORT_EMOTES_TAB(WidgetIDPlus.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDPlus.ResizableViewport.EMOTES_TAB),
	RESIZABLE_VIEWPORT_MUSIC_TAB(WidgetIDPlus.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDPlus.ResizableViewport.MUSIC_TAB),
	RESIZABLE_VIEWPORT_COMBAT_ICON(WidgetIDPlus.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDPlus.ResizableViewport.COMBAT_ICON),
	RESIZABLE_VIEWPORT_STATS_ICON(WidgetIDPlus.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDPlus.ResizableViewport.STATS_ICON),
	RESIZABLE_VIEWPORT_QUESTS_ICON(WidgetIDPlus.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDPlus.ResizableViewport.QUESTS_ICON),
	RESIZABLE_VIEWPORT_INVENTORY_ICON(WidgetIDPlus.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDPlus.ResizableViewport.INVENTORY_ICON),
	RESIZABLE_VIEWPORT_EQUIPMENT_ICON(WidgetIDPlus.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDPlus.ResizableViewport.EQUIPMENT_ICON),
	RESIZABLE_VIEWPORT_PRAYER_ICON(WidgetIDPlus.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDPlus.ResizableViewport.PRAYER_ICON),
	RESIZABLE_VIEWPORT_MAGIC_ICON(WidgetIDPlus.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDPlus.ResizableViewport.MAGIC_ICON),
	RESIZABLE_VIEWPORT_FRIENDS_CHAT_ICON(WidgetIDPlus.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDPlus.ResizableViewport.FRIENDS_CHAT_ICON),
	RESIZABLE_VIEWPORT_FRIENDS_ICON(WidgetIDPlus.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDPlus.ResizableViewport.FRIENDS_ICON),
	RESIZABLE_VIEWPORT_IGNORES_ICON(WidgetIDPlus.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDPlus.ResizableViewport.IGNORES_ICON),
	RESIZABLE_VIEWPORT_LOGOUT_ICON(WidgetIDPlus.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDPlus.ResizableViewport.LOGOUT_ICON),
	RESIZABLE_VIEWPORT_OPTIONS_ICON(WidgetIDPlus.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDPlus.ResizableViewport.OPTIONS_ICON),
	RESIZABLE_VIEWPORT_EMOTES_ICON(WidgetIDPlus.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDPlus.ResizableViewport.EMOTES_ICON),
	RESIZABLE_VIEWPORT_MUSIC_ICON(WidgetIDPlus.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDPlus.ResizableViewport.MUSIC_ICON),
	RESIZABLE_VIEWPORT_INTERFACE_CONTAINER(WidgetIDPlus.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDPlus.ResizableViewport.INTERFACE_CONTAINER),
	RESIZABLE_VIEWPORT_INVENTORY_CONTAINER(WidgetIDPlus.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDPlus.ResizableViewport.INVENTORY_CONTAINER),
	RESIZABLE_VIEWPORT_CHATBOX_PARENT(WidgetIDPlus.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDPlus.ResizableViewport.CHATBOX_PARENT),
	RESIZABLE_VIEWPORT_INVENTORY_PARENT(WidgetIDPlus.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDPlus.ResizableViewport.INVENTORY_PARENT),
	
	RESIZABLE_MINIMAP_WIDGET(WidgetIDPlus.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDPlus.ResizableViewportBottomLine.MINIMAP),
	RESIZABLE_MINIMAP_DRAW_AREA(WidgetIDPlus.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDPlus.ResizableViewportBottomLine.MINIMAP_DRAW_AREA),
	RESIZABLE_MINIMAP_ORB_HOLDER(WidgetIDPlus.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDPlus.ResizableViewportBottomLine.MINIMAP_ORB_HOLDER),
	RESIZABLE_MINIMAP_LOGOUT_BUTTON(WidgetIDPlus.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDPlus.ResizableViewportBottomLine.MINIMAP_LOGOUT_BUTTON),
	RESIZABLE_VIEWPORT_BOTTOM_LINE(WidgetIDPlus.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDPlus.ResizableViewportBottomLine.RESIZABLE_VIEWPORT_BOTTOM_LINE),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_LOGOUT_BUTTON(WidgetIDPlus.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDPlus.ResizableViewportBottomLine.LOGOUT_BUTTON_OVERLAY),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_QUESTS_ICON(WidgetIDPlus.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDPlus.ResizableViewportBottomLine.QUESTS_ICON),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_INVENTORY_TAB(WidgetIDPlus.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDPlus.ResizableViewportBottomLine.INVENTORY_TAB),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_INVENTORY_ICON(WidgetIDPlus.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDPlus.ResizableViewportBottomLine.INVENTORY_ICON),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_PRAYER_TAB(WidgetIDPlus.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDPlus.ResizableViewportBottomLine.PRAYER_TAB),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_MAGIC_TAB(WidgetIDPlus.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDPlus.ResizableViewportBottomLine.MAGIC_TAB),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_PRAYER_ICON(WidgetIDPlus.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDPlus.ResizableViewportBottomLine.PRAYER_ICON),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_EQUIPMENT_ICON(WidgetIDPlus.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDPlus.ResizableViewportBottomLine.EQUIP_ICON),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_COMBAT_ICON(WidgetIDPlus.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDPlus.ResizableViewportBottomLine.CMB_ICON),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_STATS_ICON(WidgetIDPlus.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDPlus.ResizableViewportBottomLine.SKILLS_ICON),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_MAGIC_ICON(WidgetIDPlus.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDPlus.ResizableViewportBottomLine.MAGIC_ICON),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_FRIEND_ICON(WidgetIDPlus.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDPlus.ResizableViewportBottomLine.FRIEND_ICON),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_FRIEND_CHAT_ICON(WidgetIDPlus.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDPlus.ResizableViewportBottomLine.FC_ICON),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_OPTIONS_ICON(WidgetIDPlus.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDPlus.ResizableViewportBottomLine.SETTINGS_ICON),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_EMOTES_ICON(WidgetIDPlus.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDPlus.ResizableViewportBottomLine.EMOTE_ICON),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_MUSIC_ICON(WidgetIDPlus.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDPlus.ResizableViewportBottomLine.MUSIC_ICON),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_INVENTORY_CONTAINER(WidgetIDPlus.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDPlus.ResizableViewportBottomLine.INVENTORY_CONTAINER),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_INTERFACE_CONTAINER(WidgetIDPlus.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDPlus.ResizableViewportBottomLine.INTERFACE_CONTAINER),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_CHATBOX_PARENT(WidgetIDPlus.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDPlus.ResizableViewportBottomLine.CHATBOX_PARENT),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_TABS1(WidgetIDPlus.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDPlus.ResizableViewportBottomLine.TABS1),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_TABS2(WidgetIDPlus.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDPlus.ResizableViewportBottomLine.TABS2),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_INVENTORY_PARENT(WidgetIDPlus.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDPlus.ResizableViewportBottomLine.INVENTORY_PARENT),
	
	PRAYER_THICK_SKIN(WidgetIDPlus.PRAYER_GROUP_ID, WidgetIDPlus.Prayer.THICK_SKIN),
	PRAYER_BURST_OF_STRENGTH(WidgetIDPlus.PRAYER_GROUP_ID, WidgetIDPlus.Prayer.BURST_OF_STRENGTH),
	PRAYER_CLARITY_OF_THOUGHT(WidgetIDPlus.PRAYER_GROUP_ID, WidgetIDPlus.Prayer.CLARITY_OF_THOUGHT),
	PRAYER_SHARP_EYE(WidgetIDPlus.PRAYER_GROUP_ID, WidgetIDPlus.Prayer.SHARP_EYE),
	PRAYER_MYSTIC_WILL(WidgetIDPlus.PRAYER_GROUP_ID, WidgetIDPlus.Prayer.MYSTIC_WILL),
	PRAYER_ROCK_SKIN(WidgetIDPlus.PRAYER_GROUP_ID, WidgetIDPlus.Prayer.ROCK_SKIN),
	PRAYER_SUPERHUMAN_STRENGTH(WidgetIDPlus.PRAYER_GROUP_ID, WidgetIDPlus.Prayer.SUPERHUMAN_STRENGTH),
	PRAYER_IMPROVED_REFLEXES(WidgetIDPlus.PRAYER_GROUP_ID, WidgetIDPlus.Prayer.IMPROVED_REFLEXES),
	PRAYER_RAPID_RESTORE(WidgetIDPlus.PRAYER_GROUP_ID, WidgetIDPlus.Prayer.RAPID_RESTORE),
	PRAYER_RAPID_HEAL(WidgetIDPlus.PRAYER_GROUP_ID, WidgetIDPlus.Prayer.RAPID_HEAL),
	PRAYER_PROTECT_ITEM(WidgetIDPlus.PRAYER_GROUP_ID, WidgetIDPlus.Prayer.PROTECT_ITEM),
	PRAYER_HAWK_EYE(WidgetIDPlus.PRAYER_GROUP_ID, WidgetIDPlus.Prayer.HAWK_EYE),
	PRAYER_MYSTIC_LORE(WidgetIDPlus.PRAYER_GROUP_ID, WidgetIDPlus.Prayer.MYSTIC_LORE),
	PRAYER_STEEL_SKIN(WidgetIDPlus.PRAYER_GROUP_ID, WidgetIDPlus.Prayer.STEEL_SKIN),
	PRAYER_ULTIMATE_STRENGTH(WidgetIDPlus.PRAYER_GROUP_ID, WidgetIDPlus.Prayer.ULTIMATE_STRENGTH),
	PRAYER_INCREDIBLE_REFLEXES(WidgetIDPlus.PRAYER_GROUP_ID, WidgetIDPlus.Prayer.INCREDIBLE_REFLEXES),
	PRAYER_PROTECT_FROM_MAGIC(WidgetIDPlus.PRAYER_GROUP_ID, WidgetIDPlus.Prayer.PROTECT_FROM_MAGIC),
	PRAYER_PROTECT_FROM_MISSILES(WidgetIDPlus.PRAYER_GROUP_ID, WidgetIDPlus.Prayer.PROTECT_FROM_MISSILES),
	PRAYER_PROTECT_FROM_MELEE(WidgetIDPlus.PRAYER_GROUP_ID, WidgetIDPlus.Prayer.PROTECT_FROM_MELEE),
	PRAYER_EAGLE_EYE(WidgetIDPlus.PRAYER_GROUP_ID, WidgetIDPlus.Prayer.EAGLE_EYE),
	PRAYER_MYSTIC_MIGHT(WidgetIDPlus.PRAYER_GROUP_ID, WidgetIDPlus.Prayer.MYSTIC_MIGHT),
	PRAYER_RETRIBUTION(WidgetIDPlus.PRAYER_GROUP_ID, WidgetIDPlus.Prayer.RETRIBUTION),
	PRAYER_REDEMPTION(WidgetIDPlus.PRAYER_GROUP_ID, WidgetIDPlus.Prayer.REDEMPTION),
	PRAYER_SMITE(WidgetIDPlus.PRAYER_GROUP_ID, WidgetIDPlus.Prayer.SMITE),
	PRAYER_PRESERVE(WidgetIDPlus.PRAYER_GROUP_ID, WidgetIDPlus.Prayer.PRESERVE),
	PRAYER_CHIVALRY(WidgetIDPlus.PRAYER_GROUP_ID, WidgetIDPlus.Prayer.CHIVALRY),
	PRAYER_PIETY(WidgetIDPlus.PRAYER_GROUP_ID, WidgetIDPlus.Prayer.PIETY),
	PRAYER_RIGOUR(WidgetIDPlus.PRAYER_GROUP_ID, WidgetIDPlus.Prayer.RIGOUR),
	PRAYER_AUGURY(WidgetIDPlus.PRAYER_GROUP_ID, WidgetIDPlus.Prayer.AUGURY),
	
	PRAYER_ANCIENT_STRENGTH(WidgetIDPlus.PRAYER_GROUP_ID, WidgetIDPlus.RuinousPrayers.ANCIENT_STRENGTH),
	PRAYER_ANCIENT_SIGHT(WidgetIDPlus.PRAYER_GROUP_ID, WidgetIDPlus.RuinousPrayers.ANCIENT_SIGHT),
	PRAYER_ANCIENT_WILL(WidgetIDPlus.PRAYER_GROUP_ID, WidgetIDPlus.RuinousPrayers.ANCIENT_WILL),
	PRAYER_TRINITAS(WidgetIDPlus.PRAYER_GROUP_ID, WidgetIDPlus.RuinousPrayers.TRINITAS),
	PRAYER_DECIMATE(WidgetIDPlus.PRAYER_GROUP_ID, WidgetIDPlus.RuinousPrayers.DECIMATE),
	PRAYER_ANNIHILATE(WidgetIDPlus.PRAYER_GROUP_ID, WidgetIDPlus.RuinousPrayers.ANNIHILATE),
	PRAYER_VAPORISE(WidgetIDPlus.PRAYER_GROUP_ID, WidgetIDPlus.RuinousPrayers.VAPORISE),
	PRAYER_DEFLECT_MELEE(WidgetIDPlus.PRAYER_GROUP_ID, WidgetIDPlus.RuinousPrayers.DEFLECT_MELEE),
	PRAYER_DEFLECT_RANGED(WidgetIDPlus.PRAYER_GROUP_ID, WidgetIDPlus.RuinousPrayers.DEFLECT_RANGED),
	PRAYER_DEFLECT_MAGIC(WidgetIDPlus.PRAYER_GROUP_ID, WidgetIDPlus.RuinousPrayers.DEFLECT_MAGIC),
	PRAYER_PURGE(WidgetIDPlus.PRAYER_GROUP_ID, WidgetIDPlus.RuinousPrayers.PURGE),
	PRAYER_REJUVENATION(WidgetIDPlus.PRAYER_GROUP_ID, WidgetIDPlus.RuinousPrayers.REJUVENATION),
	PRAYER_RUINOUS_GRACE(WidgetIDPlus.PRAYER_GROUP_ID, WidgetIDPlus.RuinousPrayers.RUINOUS_GRACE),
	PRAYER_WRATH(WidgetIDPlus.PRAYER_GROUP_ID, WidgetIDPlus.RuinousPrayers.WRATH),
	PRAYER_METABOLISE(WidgetIDPlus.PRAYER_GROUP_ID, WidgetIDPlus.RuinousPrayers.METABOLISE),
	PRAYER_BERSERKER(WidgetIDPlus.PRAYER_GROUP_ID, WidgetIDPlus.RuinousPrayers.BERSERKER),
	PRAYER_FUMUS_VOW(WidgetIDPlus.PRAYER_GROUP_ID, WidgetIDPlus.RuinousPrayers.FUMUS_VOW),
	PRAYER_CRUORS_VOW(WidgetIDPlus.PRAYER_GROUP_ID, WidgetIDPlus.RuinousPrayers.CRUORS_VOW),
	PRAYER_UMBRAS_VOW(WidgetIDPlus.PRAYER_GROUP_ID, WidgetIDPlus.RuinousPrayers.UMBRAS_VOW),
	PRAYER_GLACIES_VOW(WidgetIDPlus.PRAYER_GROUP_ID, WidgetIDPlus.RuinousPrayers.GLACIES_VOW),
	PRAYER_GAMBIT(WidgetIDPlus.PRAYER_GROUP_ID, WidgetIDPlus.RuinousPrayers.GAMBIT),
	PRAYER_REBUKE(WidgetIDPlus.PRAYER_GROUP_ID, WidgetIDPlus.RuinousPrayers.REBUKE),
	PRAYER_VINDICATION(WidgetIDPlus.PRAYER_GROUP_ID, WidgetIDPlus.RuinousPrayers.VINDICATION),
	
	QUICK_PRAYER_PRAYERS(WidgetIDPlus.QUICK_PRAYERS_GROUP_ID, WidgetIDPlus.QuickPrayer.PRAYERS),
	
	COMBAT_LEVEL(WidgetIDPlus.COMBAT_GROUP_ID, WidgetIDPlus.Combat.LEVEL),
	COMBAT_STYLE_ONE(WidgetIDPlus.COMBAT_GROUP_ID, WidgetIDPlus.Combat.STYLE_ONE),
	COMBAT_STYLE_TWO(WidgetIDPlus.COMBAT_GROUP_ID, WidgetIDPlus.Combat.STYLE_TWO),
	COMBAT_STYLE_THREE(WidgetIDPlus.COMBAT_GROUP_ID, WidgetIDPlus.Combat.STYLE_THREE),
	COMBAT_STYLE_FOUR(WidgetIDPlus.COMBAT_GROUP_ID, WidgetIDPlus.Combat.STYLE_FOUR),
	COMBAT_SPELLS(WidgetIDPlus.COMBAT_GROUP_ID, WidgetIDPlus.Combat.SPELLS),
	COMBAT_DEFENSIVE_SPELL_BOX(WidgetIDPlus.COMBAT_GROUP_ID, WidgetIDPlus.Combat.DEFENSIVE_SPELL_BOX),
	COMBAT_DEFENSIVE_SPELL_ICON(WidgetIDPlus.COMBAT_GROUP_ID, WidgetIDPlus.Combat.DEFENSIVE_SPELL_ICON),
	COMBAT_DEFENSIVE_SPELL_SHIELD(WidgetIDPlus.COMBAT_GROUP_ID, WidgetIDPlus.Combat.DEFENSIVE_SPELL_SHIELD),
	COMBAT_DEFENSIVE_SPELL_TEXT(WidgetIDPlus.COMBAT_GROUP_ID, WidgetIDPlus.Combat.DEFENSIVE_SPELL_TEXT),
	COMBAT_SPELL_BOX(WidgetIDPlus.COMBAT_GROUP_ID, WidgetIDPlus.Combat.SPELL_BOX),
	COMBAT_SPELL_ICON(WidgetIDPlus.COMBAT_GROUP_ID, WidgetIDPlus.Combat.SPELL_ICON),
	COMBAT_SPELL_TEXT(WidgetIDPlus.COMBAT_GROUP_ID, WidgetIDPlus.Combat.SPELL_TEXT),
	COMBAT_AUTO_RETALIATE(WidgetIDPlus.COMBAT_GROUP_ID, WidgetIDPlus.Combat.AUTO_RETALIATE),
	
	DIALOG_OPTION(WidgetIDPlus.DIALOG_OPTION_GROUP_ID, 0),
	DIALOG_OPTION_OPTIONS(WidgetIDPlus.DIALOG_OPTION_GROUP_ID, WidgetIDPlus.DialogOption.OPTIONS),
	
	DIALOG_SPRITE(WidgetIDPlus.DIALOG_SPRITE_GROUP_ID, 0),
	DIALOG_SPRITE_SPRITE(WidgetIDPlus.DIALOG_SPRITE_GROUP_ID, WidgetIDPlus.DialogSprite.SPRITE),
	DIALOG_SPRITE_TEXT(WidgetIDPlus.DIALOG_SPRITE_GROUP_ID, WidgetIDPlus.DialogSprite.TEXT),
	
	DIALOG_NPC_NAME(WidgetIDPlus.DIALOG_NPC_GROUP_ID, WidgetIDPlus.DialogNPC.NAME),
	DIALOG_NPC_TEXT(WidgetIDPlus.DIALOG_NPC_GROUP_ID, WidgetIDPlus.DialogNPC.TEXT),
	DIALOG_NPC_HEAD_MODEL(WidgetIDPlus.DIALOG_NPC_GROUP_ID, WidgetIDPlus.DialogNPC.HEAD_MODEL),
	
	DIALOG_PLAYER(WidgetIDPlus.DIALOG_PLAYER_GROUP_ID, 0),
	DIALOG_PLAYER_TEXT(WidgetIDPlus.DIALOG_PLAYER_GROUP_ID, WidgetIDPlus.DialogPlayer.TEXT),
	
	PRIVATE_CHAT_MESSAGE(WidgetIDPlus.PRIVATE_CHAT, 0),
	
	SLAYER_REWARDS_TOPBAR(WidgetIDPlus.SLAYER_REWARDS_GROUP_ID, WidgetIDPlus.SlayerRewards.TOP_BAR),
	
	CHATBOX_PARENT(WidgetIDPlus.CHATBOX_GROUP_ID, WidgetIDPlus.Chatbox.PARENT),
	CHATBOX(WidgetIDPlus.CHATBOX_GROUP_ID, WidgetIDPlus.Chatbox.FRAME),
	CHATBOX_MESSAGES(WidgetIDPlus.CHATBOX_GROUP_ID, WidgetIDPlus.Chatbox.MESSAGES),
	CHATBOX_BUTTONS(WidgetIDPlus.CHATBOX_GROUP_ID, WidgetIDPlus.Chatbox.BUTTONS),
	CHATBOX_TITLE(WidgetIDPlus.CHATBOX_GROUP_ID, WidgetIDPlus.Chatbox.TITLE),
	CHATBOX_FULL_INPUT(WidgetIDPlus.CHATBOX_GROUP_ID, WidgetIDPlus.Chatbox.FULL_INPUT),
	CHATBOX_GE_SEARCH_RESULTS(WidgetIDPlus.CHATBOX_GROUP_ID, WidgetIDPlus.Chatbox.GE_SEARCH_RESULTS),
	CHATBOX_CONTAINER(WidgetIDPlus.CHATBOX_GROUP_ID, WidgetIDPlus.Chatbox.CONTAINER),
	CHATBOX_REPORT_TEXT(WidgetIDPlus.CHATBOX_GROUP_ID, WidgetIDPlus.Chatbox.REPORT_TEXT),
	CHATBOX_INPUT(WidgetIDPlus.CHATBOX_GROUP_ID, WidgetIDPlus.Chatbox.INPUT),
	CHATBOX_TRANSPARENT_BACKGROUND(WidgetIDPlus.CHATBOX_GROUP_ID, WidgetIDPlus.Chatbox.TRANSPARENT_BACKGROUND),
	CHATBOX_TRANSPARENT_LINES(WidgetIDPlus.CHATBOX_GROUP_ID, WidgetIDPlus.Chatbox.TRANSPARENT_BACKGROUND_LINES),
	CHATBOX_MESSAGE_LINES(WidgetIDPlus.CHATBOX_GROUP_ID, WidgetIDPlus.Chatbox.MESSAGE_LINES),
	CHATBOX_FIRST_MESSAGE(WidgetIDPlus.CHATBOX_GROUP_ID, WidgetIDPlus.Chatbox.FIRST_MESSAGE),
	CHATBOX_TAB_ALL(WidgetIDPlus.CHATBOX_GROUP_ID, WidgetIDPlus.Chatbox.TAB_ALL),
	CHATBOX_TAB_GAME(WidgetIDPlus.CHATBOX_GROUP_ID, WidgetIDPlus.Chatbox.TAB_GAME),
	CHATBOX_TAB_PUBLIC(WidgetIDPlus.CHATBOX_GROUP_ID, WidgetIDPlus.Chatbox.TAB_PUBLIC),
	CHATBOX_TAB_PRIVATE(WidgetIDPlus.CHATBOX_GROUP_ID, WidgetIDPlus.Chatbox.TAB_PRIVATE),
	CHATBOX_TAB_CHANNEL(WidgetIDPlus.CHATBOX_GROUP_ID, WidgetIDPlus.Chatbox.TAB_CHANNEL),
	CHATBOX_TAB_CLAN(WidgetIDPlus.CHATBOX_GROUP_ID, WidgetIDPlus.Chatbox.TAB_CLAN),
	CHATBOX_TAB_TRADE(WidgetIDPlus.CHATBOX_GROUP_ID, WidgetIDPlus.Chatbox.TAB_TRADE),
	
	BA_TEAM(WidgetIDPlus.BA_TEAM_GROUP_ID, WidgetIDPlus.BarbarianAssault.TEAM),
	
	BA_HEAL_ROLE_TEXT(WidgetIDPlus.BA_HEALER_GROUP_ID, WidgetIDPlus.BarbarianAssault.ROLE),
	BA_HEAL_ROLE_SPRITE(WidgetIDPlus.BA_HEALER_GROUP_ID, WidgetIDPlus.BarbarianAssault.ROLE_SPRITE),
	
	BA_HEAL_TEAMMATES(WidgetIDPlus.BA_HEALER_GROUP_ID, WidgetIDPlus.BarbarianAssault.HLR.TEAMMATES),
	BA_HEAL_TEAMMATE1(WidgetIDPlus.BA_HEALER_GROUP_ID, WidgetIDPlus.BarbarianAssault.HLR.TEAMMATE1),
	BA_HEAL_TEAMMATE2(WidgetIDPlus.BA_HEALER_GROUP_ID, WidgetIDPlus.BarbarianAssault.HLR.TEAMMATE2),
	BA_HEAL_TEAMMATE3(WidgetIDPlus.BA_HEALER_GROUP_ID, WidgetIDPlus.BarbarianAssault.HLR.TEAMMATE3),
	BA_HEAL_TEAMMATE4(WidgetIDPlus.BA_HEALER_GROUP_ID, WidgetIDPlus.BarbarianAssault.HLR.TEAMMATE4),
	
	BA_COLL_ROLE_TEXT(WidgetIDPlus.BA_COLLECTOR_GROUP_ID, WidgetIDPlus.BarbarianAssault.ROLE),
	BA_COLL_ROLE_SPRITE(WidgetIDPlus.BA_COLLECTOR_GROUP_ID, WidgetIDPlus.BarbarianAssault.ROLE_SPRITE),
	
	BA_ATK_ROLE_TEXT(WidgetIDPlus.BA_ATTACKER_GROUP_ID, WidgetIDPlus.BarbarianAssault.ATK.ROLE),
	BA_ATK_ROLE_SPRITE(WidgetIDPlus.BA_ATTACKER_GROUP_ID, WidgetIDPlus.BarbarianAssault.ATK.ROLE_SPRITE),
	
	BA_DEF_ROLE_TEXT(WidgetIDPlus.BA_DEFENDER_GROUP_ID, WidgetIDPlus.BarbarianAssault.ROLE),
	BA_DEF_ROLE_SPRITE(WidgetIDPlus.BA_DEFENDER_GROUP_ID, WidgetIDPlus.BarbarianAssault.ROLE_SPRITE),
	
	BA_REWARD_TEXT(WidgetIDPlus.BA_REWARD_GROUP_ID, WidgetIDPlus.BarbarianAssault.REWARD_TEXT),
	
	LEVEL_UP(WidgetIDPlus.LEVEL_UP_GROUP_ID, 0),
	LEVEL_UP_SKILL(WidgetIDPlus.LEVEL_UP_GROUP_ID, WidgetIDPlus.LevelUp.SKILL),
	LEVEL_UP_LEVEL(WidgetIDPlus.LEVEL_UP_GROUP_ID, WidgetIDPlus.LevelUp.LEVEL),
	
	QUEST_COMPLETED(WidgetIDPlus.QUEST_COMPLETED_GROUP_ID, 0),
	QUEST_COMPLETED_NAME_TEXT(WidgetIDPlus.QUEST_COMPLETED_GROUP_ID, WidgetIDPlus.QuestCompleted.NAME_TEXT),
	
	MOTHERLODE_MINE(WidgetIDPlus.MOTHERLODE_MINE_GROUP_ID, 0),
	
	GWD_KC(WidgetIDPlus.GWD_KC_GROUP_ID, 5),
	
	PUZZLE_BOX(WidgetIDPlus.PUZZLE_BOX_GROUP_ID, WidgetIDPlus.PuzzleBox.VISIBLE_BOX),
	
	LIGHT_BOX(WidgetIDPlus.LIGHT_BOX_GROUP_ID, WidgetIDPlus.LightBox.LIGHT_BOX),
	LIGHT_BOX_CONTENTS(WidgetIDPlus.LIGHT_BOX_GROUP_ID, WidgetIDPlus.LightBox.LIGHT_BULB_CONTAINER),
	LIGHT_BOX_BUTTON_A(WidgetIDPlus.LIGHT_BOX_GROUP_ID, WidgetIDPlus.LightBox.BUTTON_A),
	LIGHT_BOX_BUTTON_B(WidgetIDPlus.LIGHT_BOX_GROUP_ID, WidgetIDPlus.LightBox.BUTTON_B),
	LIGHT_BOX_BUTTON_C(WidgetIDPlus.LIGHT_BOX_GROUP_ID, WidgetIDPlus.LightBox.BUTTON_C),
	LIGHT_BOX_BUTTON_D(WidgetIDPlus.LIGHT_BOX_GROUP_ID, WidgetIDPlus.LightBox.BUTTON_D),
	LIGHT_BOX_BUTTON_E(WidgetIDPlus.LIGHT_BOX_GROUP_ID, WidgetIDPlus.LightBox.BUTTON_E),
	LIGHT_BOX_BUTTON_F(WidgetIDPlus.LIGHT_BOX_GROUP_ID, WidgetIDPlus.LightBox.BUTTON_F),
	LIGHT_BOX_BUTTON_G(WidgetIDPlus.LIGHT_BOX_GROUP_ID, WidgetIDPlus.LightBox.BUTTON_G),
	LIGHT_BOX_BUTTON_H(WidgetIDPlus.LIGHT_BOX_GROUP_ID, WidgetIDPlus.LightBox.BUTTON_H),
	
	LIGHT_BOX_WINDOW(WidgetIDPlus.LIGHT_BOX_GROUP_ID, WidgetIDPlus.LightBox.LIGHT_BOX_WINDOW),
	
	NIGHTMARE_ZONE(WidgetIDPlus.NIGHTMARE_ZONE_GROUP_ID, 0),
	
	NIGHTMARE_PILLAR_HEALTH(WidgetIDPlus.NIGHTMARE_PILLAR_HEALTH_GROUP_ID, 1),
	
	RAIDS_POINTS_INFOBOX(WidgetIDPlus.RAIDS_GROUP_ID, WidgetIDPlus.Raids.POINTS_INFOBOX),
	
	RAIDS_PRIVATE_STORAGE_ITEM_CONTAINER(WidgetIDPlus.CHAMBERS_OF_XERIC_STORAGE_UNIT_PRIVATE_GROUP_ID, WidgetIDPlus.ChambersOfXericStorageUnitPrivate.PRIVATE_CHEST_ITEM_CONTAINER),
	
	TOB_PARTY_INTERFACE(WidgetIDPlus.TOB_GROUP_ID, WidgetIDPlus.Tob.PARTY_INTERFACE),
	TOB_PARTY_STATS(WidgetIDPlus.TOB_GROUP_ID, WidgetIDPlus.Tob.PARTY_STATS),
	TOB_HEALTH_BAR(WidgetIDPlus.TOB_GROUP_ID, WidgetIDPlus.Tob.HEALTHBAR_CONTAINER),
	
	BLAST_FURNACE_COFFER(WidgetIDPlus.BLAST_FURNACE_GROUP_ID, 2),
	
	PYRAMID_PLUNDER_DATA(WidgetIDPlus.PYRAMID_PLUNDER_GROUP_ID, 2),
	
	EXPERIENCE_TRACKER(WidgetIDPlus.EXPERIENCE_TRACKER_GROUP_ID, 0),
	EXPERIENCE_TRACKER_WIDGET(WidgetIDPlus.EXPERIENCE_TRACKER_GROUP_ID, WidgetIDPlus.ExperienceTracker.WIDGET),
	EXPERIENCE_TRACKER_BOTTOM_BAR(WidgetIDPlus.EXPERIENCE_TRACKER_GROUP_ID, WidgetIDPlus.ExperienceTracker.BOTTOM_BAR),
	
	FISHING_TRAWLER_CONTRIBUTION(WidgetIDPlus.FISHING_TRAWLER_GROUP_ID, 13),
	FISHING_TRAWLER_TIMER(WidgetIDPlus.FISHING_TRAWLER_GROUP_ID, 14),
	
	TITHE_FARM(WidgetIDPlus.TITHE_FARM_GROUP_ID, 2),
	
	BARROWS_BROTHERS(WidgetIDPlus.BARROWS_GROUP_ID, WidgetIDPlus.Barrows.BARROWS_BROTHERS),
	BARROWS_POTENTIAL(WidgetIDPlus.BARROWS_GROUP_ID, WidgetIDPlus.Barrows.BARROWS_POTENTIAL),
	BARROWS_PUZZLE_PARENT(WidgetIDPlus.BARROWS_PUZZLE_GROUP_ID, WidgetIDPlus.Barrows_Puzzle.PARENT),
	BARROWS_PUZZLE_ANSWER1(WidgetIDPlus.BARROWS_PUZZLE_GROUP_ID, WidgetIDPlus.Barrows_Puzzle.ANSWER1),
	BARROWS_PUZZLE_ANSWER1_CONTAINER(WidgetIDPlus.BARROWS_PUZZLE_GROUP_ID, WidgetIDPlus.Barrows_Puzzle.ANSWER1_CONTAINER),
	BARROWS_PUZZLE_ANSWER2(WidgetIDPlus.BARROWS_PUZZLE_GROUP_ID, WidgetIDPlus.Barrows_Puzzle.ANSWER2),
	BARROWS_PUZZLE_ANSWER2_CONTAINER(WidgetIDPlus.BARROWS_PUZZLE_GROUP_ID, WidgetIDPlus.Barrows_Puzzle.ANSWER2_CONTAINER),
	BARROWS_PUZZLE_ANSWER3(WidgetIDPlus.BARROWS_PUZZLE_GROUP_ID, WidgetIDPlus.Barrows_Puzzle.ANSWER3),
	BARROWS_PUZZLE_ANSWER3_CONTAINER(WidgetIDPlus.BARROWS_PUZZLE_GROUP_ID, WidgetIDPlus.Barrows_Puzzle.ANSWER3_CONTAINER),
	BARROWS_FIRST_PUZZLE(WidgetIDPlus.BARROWS_PUZZLE_GROUP_ID, WidgetIDPlus.Barrows_Puzzle.SEQUENCE_1),
	
	BLAST_MINE(WidgetIDPlus.BLAST_MINE_GROUP_ID, 2),
	
	FAIRY_RING(WidgetIDPlus.FAIRY_RING_GROUP_ID, 0),
	
	FAIRY_RING_HEADER(WidgetIDPlus.FAIRY_RING_PANEL_GROUP_ID, WidgetIDPlus.FairyRingPanel.HEADER),
	FAIRY_RING_LIST(WidgetIDPlus.FAIRY_RING_PANEL_GROUP_ID, WidgetIDPlus.FairyRingPanel.LIST),
	FAIRY_RING_FAVORITES(WidgetIDPlus.FAIRY_RING_PANEL_GROUP_ID, WidgetIDPlus.FairyRingPanel.FAVORITES),
	FAIRY_RING_LIST_SEPARATOR(WidgetIDPlus.FAIRY_RING_PANEL_GROUP_ID, WidgetIDPlus.FairyRingPanel.SEPARATOR),
	FAIRY_RING_LIST_SCROLLBAR(WidgetIDPlus.FAIRY_RING_PANEL_GROUP_ID, WidgetIDPlus.FairyRingPanel.SCROLLBAR),
	
	DESTROY_ITEM(WidgetIDPlus.DESTROY_ITEM_GROUP_ID, 0),
	DESTROY_ITEM_NAME(WidgetIDPlus.DESTROY_ITEM_GROUP_ID, WidgetIDPlus.DestroyItem.DESTROY_ITEM_NAME),
	DESTROY_ITEM_YES(WidgetIDPlus.DESTROY_ITEM_GROUP_ID, WidgetIDPlus.DestroyItem.DESTROY_ITEM_YES),
	DESTROY_ITEM_NO(WidgetIDPlus.DESTROY_ITEM_GROUP_ID, WidgetIDPlus.DestroyItem.DESTROY_ITEM_NO),
	
	VARROCK_MUSEUM_QUESTION(WidgetIDPlus.VARROCK_MUSEUM_QUIZ_GROUP_ID, WidgetIDPlus.VarrockMuseum.VARROCK_MUSEUM_QUESTION),
	VARROCK_MUSEUM_FIRST_ANSWER(WidgetIDPlus.VARROCK_MUSEUM_QUIZ_GROUP_ID, WidgetIDPlus.VarrockMuseum.VARROCK_MUSEUM_FIRST_ANSWER),
	VARROCK_MUSEUM_SECOND_ANSWER(WidgetIDPlus.VARROCK_MUSEUM_QUIZ_GROUP_ID, WidgetIDPlus.VarrockMuseum.VARROCK_MUSEUM_SECOND_ANSWER),
	VARROCK_MUSEUM_THIRD_ANSWER(WidgetIDPlus.VARROCK_MUSEUM_QUIZ_GROUP_ID, WidgetIDPlus.VarrockMuseum.VARROCK_MUSEUM_THIRD_ANSWER),
	
	KILL_LOG_TITLE(WidgetIDPlus.KILL_LOGS_GROUP_ID, WidgetIDPlus.KillLog.TITLE),
	KILL_LOG_MONSTER(WidgetIDPlus.KILL_LOGS_GROUP_ID, WidgetIDPlus.KillLog.MONSTER),
	KILL_LOG_KILLS(WidgetIDPlus.KILL_LOGS_GROUP_ID, WidgetIDPlus.KillLog.KILLS),
	KILL_LOG_STREAK(WidgetIDPlus.KILL_LOGS_GROUP_ID, WidgetIDPlus.KillLog.STREAK),
	
	ADVENTURE_LOG(WidgetIDPlus.ADVENTURE_LOG_ID, WidgetIDPlus.AdventureLog.CONTAINER),
	
	COLLECTION_LOG(WidgetIDPlus.COLLECTION_LOG_ID, WidgetIDPlus.CollectionLog.CONTAINER),
	
	COLLECTION_LOG_TABS(WidgetIDPlus.COLLECTION_LOG_ID, WidgetIDPlus.CollectionLog.TABS),
	COLLECTION_LOG_ENTRY(WidgetIDPlus.COLLECTION_LOG_ID, WidgetIDPlus.CollectionLog.ENTRY),
	COLLECTION_LOG_ENTRY_HEADER(WidgetIDPlus.COLLECTION_LOG_ID, WidgetIDPlus.CollectionLog.ENTRY_HEADER),
	COLLECTION_LOG_ENTRY_ITEMS(WidgetIDPlus.COLLECTION_LOG_ID, WidgetIDPlus.CollectionLog.ENTRY_ITEMS),
	
	GENERIC_SCROLL_TEXT(WidgetIDPlus.GENERIC_SCROLL_GROUP_ID, WidgetIDPlus.GenericScroll.TEXT),
	
	WORLD_SWITCHER_LIST(WidgetIDPlus.WORLD_SWITCHER_GROUP_ID, WidgetIDPlus.WorldSwitcher.WORLD_LIST),
	
	FOSSIL_ISLAND_OXYGENBAR(WidgetIDPlus.FOSSIL_ISLAND_OXYGENBAR_ID, 1),
	
	MINIGAME_TELEPORT_BUTTON(WidgetIDPlus.MINIGAME_TAB_ID, WidgetIDPlus.Minigames.TELEPORT_BUTTON),
	
	SPELL_LUMBRIDGE_HOME_TELEPORT(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.StandardSpellBook.LUMBRIDGE_HOME_TELEPORT),
	SPELL_EDGEVILLE_HOME_TELEPORT(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.AncientSpellBook.EDGEVILLE_HOME_TELEPORT),
	SPELL_LUNAR_HOME_TELEPORT(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.LunarSpellBook.LUNAR_HOME_TELEPORT),
	SPELL_ARCEUUS_HOME_TELEPORT(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.ArceuusSpellBook.ARCEUUS_HOME_TELEPORT),
	SPELL_KOUREND_HOME_TELEPORT(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.StandardSpellBook.KOUREND_HOME_TELEPORT),
	SPELL_CATHERBY_HOME_TELEPORT(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.StandardSpellBook.CATHERBY_HOME_TELEPORT),
	SPELL_LUNAR_FERTILE_SOIL(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.LunarSpellBook.FERTILE_SOIL),
	
	PVP_WILDERNESS_SKULL_CONTAINER(WidgetIDPlus.PVP_GROUP_ID, WidgetIDPlus.Pvp.WILDERNESS_SKULL_CONTAINER),
	PVP_SKULL_CONTAINER(WidgetIDPlus.PVP_GROUP_ID, WidgetIDPlus.Pvp.SKULL_CONTAINER),
	PVP_WORLD_SAFE_ZONE(WidgetIDPlus.PVP_GROUP_ID, WidgetIDPlus.Pvp.SAFE_ZONE),
	
	PVP_WILDERNESS_LEVEL(WidgetIDPlus.PVP_GROUP_ID, WidgetIDPlus.Pvp.WILDERNESS_LEVEL),
	PVP_KILLDEATH_COUNTER(WidgetIDPlus.PVP_GROUP_ID, WidgetIDPlus.Pvp.KILLDEATH_RATIO),
	
	KOUREND_FAVOUR_OVERLAY(WidgetIDPlus.KOUREND_FAVOUR_GROUP_ID, WidgetIDPlus.KourendFavour.KOUREND_FAVOUR_OVERLAY),
	ZEAH_MESS_HALL_COOKING_DISPLAY(WidgetIDPlus.ZEAH_MESS_HALL_GROUP_ID, WidgetIDPlus.Zeah.MESS_HALL_COOKING_DISPLAY),
	
	LOOTING_BAG_CONTAINER(WidgetIDPlus.LOOTING_BAG_GROUP_ID, WidgetIDPlus.LootingBag.LOOTING_BAG_INVENTORY),
	
	SKOTIZO_CONTAINER(WidgetIDPlus.SKOTIZO_GROUP_ID, WidgetIDPlus.Skotizo.CONTAINER),
	
	QUESTLIST_BOX(WidgetIDPlus.QUESTLIST_GROUP_ID, WidgetIDPlus.QuestList.BOX),
	QUESTLIST_CONTAINER(WidgetIDPlus.QUESTLIST_GROUP_ID, WidgetIDPlus.QuestList.CONTAINER),
	
	SEED_VAULT_TITLE_CONTAINER(WidgetIDPlus.SEED_VAULT_GROUP_ID, WidgetIDPlus.SeedVault.TITLE_CONTAINER),
	SEED_VAULT_ITEM_CONTAINER(WidgetIDPlus.SEED_VAULT_GROUP_ID, WidgetIDPlus.SeedVault.ITEM_CONTAINER),
	SEED_VAULT_ITEM_TEXT(WidgetIDPlus.SEED_VAULT_GROUP_ID, WidgetIDPlus.SeedVault.ITEM_TEXT),
	SEED_VAULT_INVENTORY_ITEMS_CONTAINER(WidgetIDPlus.SEED_VAULT_INVENTORY_GROUP_ID, WidgetIDPlus.SeedVault.INVENTORY_ITEM_CONTAINER),
	
	SETTINGS_SIDE_CAMERA_ZOOM_SLIDER_TRACK(WidgetIDPlus.SETTINGS_SIDE_GROUP_ID, WidgetIDPlus.SettingsSide.CAMERA_ZOOM_SLIDER_TRACK),
	SETTINGS_SIDE_MUSIC_SLIDER(WidgetIDPlus.SETTINGS_SIDE_GROUP_ID, WidgetIDPlus.SettingsSide.MUSIC_SLIDER),
	SETTINGS_SIDE_SOUND_EFFECT_SLIDER(WidgetIDPlus.SETTINGS_SIDE_GROUP_ID, WidgetIDPlus.SettingsSide.SOUND_EFFECT_SLIDER),
	SETTINGS_SIDE_AREA_SOUND_SLIDER(WidgetIDPlus.SETTINGS_SIDE_GROUP_ID, WidgetIDPlus.SettingsSide.AREA_SOUND_SLIDER),
	
	SETTINGS_INIT(WidgetIDPlus.SETTINGS_GROUP_ID, WidgetIDPlus.Settings.INIT),
	
	ACHIEVEMENT_DIARY_CONTAINER(WidgetIDPlus.ACHIEVEMENT_DIARY_GROUP_ID, WidgetIDPlus.AchievementDiary.CONTAINER),
	
	SKILLS_CONTAINER(WidgetIDPlus.SKILLS_GROUP_ID, WidgetIDPlus.Skills.CONTAINER),
	
	GAUNTLET_TIMER_CONTAINER(WidgetIDPlus.GAUNTLET_TIMER_GROUP_ID, WidgetIDPlus.GauntletTimer.CONTAINER),
	HALLOWED_SEPULCHRE_TIMER_CONTAINER(WidgetIDPlus.HALLOWED_SEPULCHRE_TIMER_GROUP_ID, WidgetIDPlus.HallowedSepulchreTimer.CONTAINER),
	
	HEALTH_OVERLAY_BAR(WidgetIDPlus.HEALTH_OVERLAY_BAR_GROUP_ID, WidgetIDPlus.Health.HEALTHBAR_CONTAINER),
	HEALTH_OVERLAY_BAR_TEXT(WidgetIDPlus.HEALTH_OVERLAY_BAR_GROUP_ID, WidgetIDPlus.Health.HEALTHBAR_TEXT),
	
	TRAILBLAZER_AREA_TELEPORT(WidgetIDPlus.TRAILBLAZER_AREAS_GROUP_ID, WidgetIDPlus.TrailblazerAreas.TELEPORT),
	
	MULTICOMBAT_FIXED(WidgetIDPlus.FIXED_VIEWPORT_GROUP_ID, WidgetIDPlus.FixedViewport.MULTICOMBAT_INDICATOR),
	MULTICOMBAT_RESIZABLE_MODERN(WidgetIDPlus.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDPlus.ResizableViewport.MULTICOMBAT_INDICATOR),
	MULTICOMBAT_RESIZABLE_CLASSIC(WidgetIDPlus.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDPlus.ResizableViewport.MULTICOMBAT_INDICATOR),
	
	TEMPOROSS_STATUS_INDICATOR(WidgetIDPlus.TEMPOROSS_GROUP_ID, WidgetIDPlus.TemporossStatus.STATUS_INDICATOR),
	
	CLAN_LAYER(WidgetIDPlus.CLAN_GROUP_ID, WidgetIDPlus.Clan.LAYER),
	CLAN_HEADER(WidgetIDPlus.CLAN_GROUP_ID, WidgetIDPlus.Clan.HEADER),
	CLAN_MEMBER_LIST(WidgetIDPlus.CLAN_GROUP_ID, WidgetIDPlus.Clan.MEMBERS),
	
	CLAN_GUEST_LAYER(WidgetIDPlus.CLAN_GUEST_GROUP_ID, WidgetIDPlus.ClanGuest.LAYER),
	CLAN_GUEST_HEADER(WidgetIDPlus.CLAN_GUEST_GROUP_ID, WidgetIDPlus.ClanGuest.HEADER),
	CLAN_GUEST_MEMBER_LIST(WidgetIDPlus.CLAN_GUEST_GROUP_ID, WidgetIDPlus.ClanGuest.MEMBERS),
	
	//OpenOSRS
	WORLD_MAP_BUTTON_BORDER(WidgetIDPlus.MINIMAP_GROUP_ID, WidgetIDPlus.Minimap.WORLDMAP_ORB),
	
	EQUIPMENT_HELMET(WidgetIDPlus.EQUIPMENT_GROUP_ID, WidgetIDPlus.Equipment.HELMET),
	EQUIPMENT_CAPE(WidgetIDPlus.EQUIPMENT_GROUP_ID, WidgetIDPlus.Equipment.CAPE),
	EQUIPMENT_AMULET(WidgetIDPlus.EQUIPMENT_GROUP_ID, WidgetIDPlus.Equipment.AMULET),
	EQUIPMENT_WEAPON(WidgetIDPlus.EQUIPMENT_GROUP_ID, WidgetIDPlus.Equipment.WEAPON),
	EQUIPMENT_BODY(WidgetIDPlus.EQUIPMENT_GROUP_ID, WidgetIDPlus.Equipment.BODY),
	EQUIPMENT_SHIELD(WidgetIDPlus.EQUIPMENT_GROUP_ID, WidgetIDPlus.Equipment.SHIELD),
	EQUIPMENT_LEGS(WidgetIDPlus.EQUIPMENT_GROUP_ID, WidgetIDPlus.Equipment.LEGS),
	EQUIPMENT_GLOVES(WidgetIDPlus.EQUIPMENT_GROUP_ID, WidgetIDPlus.Equipment.GLOVES),
	EQUIPMENT_BOOTS(WidgetIDPlus.EQUIPMENT_GROUP_ID, WidgetIDPlus.Equipment.BOOTS),
	EQUIPMENT_RING(WidgetIDPlus.EQUIPMENT_GROUP_ID, WidgetIDPlus.Equipment.RING),
	EQUIPMENT_AMMO(WidgetIDPlus.EQUIPMENT_GROUP_ID, WidgetIDPlus.Equipment.AMMO),
	
	MINIGAME_DIALOG(WidgetIDPlus.DIALOG_MINIGAME_GROUP_ID, 0),
	MINIGAME_DIALOG_TEXT(WidgetIDPlus.DIALOG_MINIGAME_GROUP_ID, WidgetIDPlus.MinigameDialog.TEXT),
	MINIGAME_DIALOG_CONTINUE(WidgetIDPlus.DIALOG_MINIGAME_GROUP_ID, WidgetIDPlus.MinigameDialog.CONTINUE),
	PEST_CONTROL_EXCHANGE_WINDOW(WidgetIDPlus.PEST_CONTROL_EXCHANGE_WINDOW_GROUP_ID, 0),
	PEST_CONTROL_EXCHANGE_WINDOW_POINTS(WidgetIDPlus.PEST_CONTROL_EXCHANGE_WINDOW_GROUP_ID, WidgetIDPlus.PestControlExchangeWindow.POINTS),
	
	GRAND_EXCHANGE_HISTORY_BUTTON(WidgetIDPlus.GRAND_EXCHANGE_GROUP_ID, WidgetIDPlus.GrandExchange.HISTORY_BUTTON),
	GRAND_EXCHANGE_BACK_BUTTON(WidgetIDPlus.GRAND_EXCHANGE_GROUP_ID, WidgetIDPlus.GrandExchange.BACK_BUTTON),
	GRAND_EXCHANGE_OFFER1(WidgetIDPlus.GRAND_EXCHANGE_GROUP_ID, WidgetIDPlus.GrandExchange.OFFER1),
	GRAND_EXCHANGE_OFFER2(WidgetIDPlus.GRAND_EXCHANGE_GROUP_ID, WidgetIDPlus.GrandExchange.OFFER2),
	GRAND_EXCHANGE_OFFER3(WidgetIDPlus.GRAND_EXCHANGE_GROUP_ID, WidgetIDPlus.GrandExchange.OFFER3),
	GRAND_EXCHANGE_OFFER4(WidgetIDPlus.GRAND_EXCHANGE_GROUP_ID, WidgetIDPlus.GrandExchange.OFFER4),
	GRAND_EXCHANGE_OFFER5(WidgetIDPlus.GRAND_EXCHANGE_GROUP_ID, WidgetIDPlus.GrandExchange.OFFER5),
	GRAND_EXCHANGE_OFFER6(WidgetIDPlus.GRAND_EXCHANGE_GROUP_ID, WidgetIDPlus.GrandExchange.OFFER6),
	GRAND_EXCHANGE_OFFER7(WidgetIDPlus.GRAND_EXCHANGE_GROUP_ID, WidgetIDPlus.GrandExchange.OFFER7),
	GRAND_EXCHANGE_OFFER8(WidgetIDPlus.GRAND_EXCHANGE_GROUP_ID, WidgetIDPlus.GrandExchange.OFFER8),
	
	GRAND_EXCHANGE_OFFER_CONFIRM_BUTTON(WidgetIDPlus.GRAND_EXCHANGE_GROUP_ID, WidgetIDPlus.GrandExchange.OFFER_CONFIRM_BUTTON),
	
	SMITHING_ANVIL_DAGGER(WidgetIDPlus.SMITHING_GROUP_ID, WidgetIDPlus.Smithing.DAGGER),
	SMITHING_ANVIL_SWORD(WidgetIDPlus.SMITHING_GROUP_ID, WidgetIDPlus.Smithing.SWORD),
	SMITHING_ANVIL_SCIMITAR(WidgetIDPlus.SMITHING_GROUP_ID, WidgetIDPlus.Smithing.SCIMITAR),
	SMITHING_ANVIL_LONG_SWORD(WidgetIDPlus.SMITHING_GROUP_ID, WidgetIDPlus.Smithing.LONG_SWORD),
	SMITHING_ANVIL_TWO_H_SWORD(WidgetIDPlus.SMITHING_GROUP_ID, WidgetIDPlus.Smithing.TWO_H_SWORD),
	SMITHING_ANVIL_AXE(WidgetIDPlus.SMITHING_GROUP_ID, WidgetIDPlus.Smithing.AXE),
	SMITHING_ANVIL_MACE(WidgetIDPlus.SMITHING_GROUP_ID, WidgetIDPlus.Smithing.MACE),
	SMITHING_ANVIL_WARHAMMER(WidgetIDPlus.SMITHING_GROUP_ID, WidgetIDPlus.Smithing.WARHAMMER),
	SMITHING_ANVIL_BATTLE_AXE(WidgetIDPlus.SMITHING_GROUP_ID, WidgetIDPlus.Smithing.BATTLE_AXE),
	SMITHING_ANVIL_CLAWS(WidgetIDPlus.SMITHING_GROUP_ID, WidgetIDPlus.Smithing.CLAWS),
	SMITHING_ANVIL_CHAIN_BODY(WidgetIDPlus.SMITHING_GROUP_ID, WidgetIDPlus.Smithing.CHAIN_BODY),
	SMITHING_ANVIL_PLATE_LEGS(WidgetIDPlus.SMITHING_GROUP_ID, WidgetIDPlus.Smithing.PLATE_LEGS),
	SMITHING_ANVIL_PLATE_SKIRT(WidgetIDPlus.SMITHING_GROUP_ID, WidgetIDPlus.Smithing.PLATE_SKIRT),
	SMITHING_ANVIL_PLATE_BODY(WidgetIDPlus.SMITHING_GROUP_ID, WidgetIDPlus.Smithing.PLATE_BODY),
	SMITHING_ANVIL_NAILS(WidgetIDPlus.SMITHING_GROUP_ID, WidgetIDPlus.Smithing.NAILS),
	SMITHING_ANVIL_MED_HELM(WidgetIDPlus.SMITHING_GROUP_ID, WidgetIDPlus.Smithing.MED_HELM),
	SMITHING_ANVIL_FULL_HELM(WidgetIDPlus.SMITHING_GROUP_ID, WidgetIDPlus.Smithing.FULL_HELM),
	SMITHING_ANVIL_SQ_SHIELD(WidgetIDPlus.SMITHING_GROUP_ID, WidgetIDPlus.Smithing.SQ_SHIELD),
	SMITHING_ANVIL_KITE_SHIELD(WidgetIDPlus.SMITHING_GROUP_ID, WidgetIDPlus.Smithing.KITE_SHIELD),
	SMITHING_ANVIL_DART_TIPS(WidgetIDPlus.SMITHING_GROUP_ID, WidgetIDPlus.Smithing.DART_TIPS),
	SMITHING_ANVIL_ARROW_HEADS(WidgetIDPlus.SMITHING_GROUP_ID, WidgetIDPlus.Smithing.ARROW_HEADS),
	SMITHING_ANVIL_KNIVES(WidgetIDPlus.SMITHING_GROUP_ID, WidgetIDPlus.Smithing.KNIVES),
	SMITHING_ANVIL_JAVELIN_HEADS(WidgetIDPlus.SMITHING_GROUP_ID, WidgetIDPlus.Smithing.JAVELIN_HEADS),
	SMITHING_ANVIL_BOLTS(WidgetIDPlus.SMITHING_GROUP_ID, WidgetIDPlus.Smithing.BOLTS),
	SMITHING_ANVIL_LIMBS(WidgetIDPlus.SMITHING_GROUP_ID, WidgetIDPlus.Smithing.LIMBS),
	SMITHING_ANVIL_EXCLUSIVE1(WidgetIDPlus.SMITHING_GROUP_ID, WidgetIDPlus.Smithing.EXCLUSIVE1),
	SMITHING_ANVIL_EXCLUSIVE2(WidgetIDPlus.SMITHING_GROUP_ID, WidgetIDPlus.Smithing.EXCLUSIVE2),
	
	MINIMAP_WORLD_ORB(WidgetIDPlus.MINIMAP_GROUP_ID, WidgetIDPlus.Minimap.WORLDMAP_ORB),
	
	COMBAT_WEAPON(WidgetIDPlus.COMBAT_GROUP_ID, WidgetIDPlus.Combat.WEAPON_NAME),
	
	COMBAT_SPECIAL_ATTACK(WidgetIDPlus.COMBAT_GROUP_ID, WidgetIDPlus.Combat.SPECIAL_ATTACK_BAR),
	COMBAT_SPECIAL_ATTACK_CLICKBOX(WidgetIDPlus.COMBAT_GROUP_ID, WidgetIDPlus.Combat.SPECIAL_ATTACK_CLICKBOX),
	COMBAT_TOOLTIP(WidgetIDPlus.COMBAT_GROUP_ID, WidgetIDPlus.Combat.TOOLTIP),
	
	MULTI_SKILL_MENU(WidgetIDPlus.MULTISKILL_MENU_GROUP_ID, 0),
	
	DIALOG2_SPRITE(WidgetIDPlus.DIALOG_SPRITE2_ID, 0),
	DIALOG2_SPRITE_SPRITE1(WidgetIDPlus.DIALOG_SPRITE2_ID, WidgetIDPlus.DialogSprite2.SPRITE1),
	DIALOG2_SPRITE_SPRITE2(WidgetIDPlus.DIALOG_SPRITE2_ID, WidgetIDPlus.DialogSprite2.SPRITE2),
	DIALOG2_SPRITE_TEXT(WidgetIDPlus.DIALOG_SPRITE2_ID, WidgetIDPlus.DialogSprite2.TEXT),
	DIALOG2_SPRITE_CONTINUE(WidgetIDPlus.DIALOG_SPRITE2_ID, WidgetIDPlus.DialogSprite2.CONTINUE),
	
	DIALOG_OPTION_OPTION1(WidgetIDPlus.DIALOG_OPTION_GROUP_ID, WidgetIDPlus.DialogOption.OPTIONS),
	
	DIALOG_NOTIFICATION_TEXT(WidgetIDPlus.DIALOG_NOTIFICATION_GROUP_ID, WidgetIDPlus.DialogNotification.TEXT),
	DIALOG_NOTIFICATION_CONTINUE(WidgetIDPlus.DIALOG_NOTIFICATION_GROUP_ID, WidgetIDPlus.DialogNotification.CONTINUE),
	
	LEVEL_UP_CONTINUE(WidgetIDPlus.LEVEL_UP_GROUP_ID, WidgetIDPlus.LevelUp.CONTINUE),
	
	THEATRE_OF_BLOOD_PARTY(WidgetIDPlus.THEATRE_OF_BLOOD_PARTY_GROUP_ID, WidgetIDPlus.TheatreOfBloodParty.CONTAINER),
	
	LIGHT_BOX_BUTTON_CONTAINER(WidgetIDPlus.LIGHT_BOX_GROUP_ID, WidgetIDPlus.LightBox.LIGHT_BOX_BUTTON_CONTAINER),
	
	THEATRE_OF_BLOOD_HEALTH_ORBS(WidgetIDPlus.THEATRE_OF_BLOOD_GROUP_ID, WidgetIDPlus.TheatreOfBlood.ORB_BOX),
	THEATRE_OF_BLOOD_BOSS_HEALTH(WidgetIDPlus.THEATRE_OF_BLOOD_GROUP_ID, WidgetIDPlus.TheatreOfBlood.BOSS_HEALTH_BAR),
	THEATRE_OF_BLOOD_RAIDING_PARTY(WidgetIDPlus.THEATRE_OF_BLOOD_GROUP_ID, WidgetIDPlus.TheatreOfBlood.RAIDING_PARTY),
	
	WORLD_SWITCHER_CONTAINER(WidgetIDPlus.WORLD_SWITCHER_GROUP_ID, WidgetIDPlus.WorldSwitcher.CONTAINER),
	
	WORLD_SWITCHER_LOGOUT_BUTTON(WidgetIDPlus.WORLD_SWITCHER_GROUP_ID, WidgetIDPlus.WorldSwitcher.LOGOUT_BUTTON),
	
	FOSSIL_MUSHROOM_TELEPORT(WidgetIDPlus.FOSSIL_ISLAND_MUSHROOM_TELE_GROUP_ID, WidgetIDPlus.FossilMushroomTeleport.ROOT),
	FOSSIL_MUSHROOM_HOUSE(WidgetIDPlus.FOSSIL_ISLAND_MUSHROOM_TELE_GROUP_ID, WidgetIDPlus.FossilMushroomTeleport.HOUSE_ON_HILL),
	FOSSIL_MUSHROOM_VALLEY(WidgetIDPlus.FOSSIL_ISLAND_MUSHROOM_TELE_GROUP_ID, WidgetIDPlus.FossilMushroomTeleport.VERDANT_VALLEY),
	FOSSIL_MUSHROOM_SWAMP(WidgetIDPlus.FOSSIL_ISLAND_MUSHROOM_TELE_GROUP_ID, WidgetIDPlus.FossilMushroomTeleport.SWAMP),
	FOSSIL_MUSHROOM_MEADOW(WidgetIDPlus.FOSSIL_ISLAND_MUSHROOM_TELE_GROUP_ID, WidgetIDPlus.FossilMushroomTeleport.MUSHROOM_MEADOW),
	
	SPELLBOOK(WidgetIDPlus.SPELLBOOK_GROUP_ID, 0),
	SPELLBOOK_FILTERED_BOUNDS(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.FILTERED_SPELLS_BOUNDS),
	
	/* STANDARD SPELL BOOK WIDGETS*/
	SPELL_WIND_STRIKE(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.WIND_STRIKE),
	SPELL_CONFUSE(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.CONFUSE),
	SPELL_ENCHANT_CROSSBOW_BOLT(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.ENCHANT_CROSSBOW_BOLT),
	SPELL_WATER_STRIKE(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.WATER_STRIKE),
	SPELL_LVL_1_ENCHANT(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.LVL_1_ENCHANT),
	SPELL_EARTH_STRIKE(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.EARTH_STRIKE),
	SPELL_WEAKEN(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.WEAKEN),
	SPELL_FIRE_STRIKE(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.FIRE_STRIKE),
	SPELL_BONES_TO_BANANAS(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.BONES_TO_BANANAS),
	SPELL_WIND_BOLT(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.WIND_BOLT),
	SPELL_CURSE(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.CURSE),
	SPELL_BIND(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.BIND),
	SPELL_LOW_LEVEL_ALCHEMY(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.LOW_LEVEL_ALCHEMY),
	SPELL_WATER_BOLT(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.WATER_BOLT),
	SPELL_VARROCK_TELEPORT(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.VARROCK_TELEPORT),
	SPELL_LVL_2_ENCHANT(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.LVL_2_ENCHANT),
	SPELL_EARTH_BOLT(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.EARTH_BOLT),
	SPELL_LUMBRIDGE_TELEPORT(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.LUMBRIDGE_TELEPORT),
	SPELL_TELEKINETIC_GRAB(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.TELEKINETIC_GRAB),
	SPELL_FIRE_BOLT(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.FIRE_BOLT),
	SPELL_FALADOR_TELEPORT(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.FALADOR_TELEPORT),
	SPELL_CRUMBLE_UNDEAD(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.CRUMBLE_UNDEAD),
	SPELL_TELEPORT_TO_HOUSE(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.TELEPORT_TO_HOUSE),
	SPELL_WIND_BLAST(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.WIND_BLAST),
	SPELL_SUPERHEAT_ITEM(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.SUPERHEAT_ITEM),
	SPELL_CAMELOT_TELEPORT(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.CAMELOT_TELEPORT),
	SPELL_WATER_BLAST(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.WATER_BLAST),
	SPELL_LVL_3_ENCHANT(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.LVL_3_ENCHANT),
	SPELL_IBAN_BLAST(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.IBAN_BLAST),
	SPELL_SNARE(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.SNARE),
	SPELL_MAGIC_DART(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.MAGIC_DART),
	SPELL_ARDOUGNE_TELEPORT(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.ARDOUGNE_TELEPORT),
	SPELL_EARTH_BLAST(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.EARTH_BLAST),
	SPELL_HIGH_LEVEL_ALCHEMY(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.HIGH_LEVEL_ALCHEMY),
	SPELL_CHARGE_WATER_ORB(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.CHARGE_WATER_ORB),
	SPELL_LVL_4_ENCHANT(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.LVL_4_ENCHANT),
	SPELL_WATCHTOWER_TELEPORT(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.WATCHTOWER_TELEPORT),
	SPELL_FIRE_BLAST(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.FIRE_BLAST),
	SPELL_CHARGE_EARTH_ORB(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.CHARGE_EARTH_ORB),
	SPELL_BONES_TO_PEACHES(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.BONES_TO_PEACHES),
	SPELL_SARADOMIN_STRIKE(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.SARADOMIN_STRIKE),
	SPELL_CLAWS_OF_GUTHIX(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.CLAWS_OF_GUTHIX),
	SPELL_FLAMES_OF_ZAMORAK(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.FLAMES_OF_ZAMORAK),
	SPELL_TROLLHEIM_TELEPORT(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.TROLLHEIM_TELEPORT),
	SPELL_WIND_WAVE(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.WIND_WAVE),
	SPELL_CHARGE_FIRE_ORB(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.CHARGE_FIRE_ORB),
	SPELL_TELEPORT_TO_APE_ATOLL(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.TELEPORT_TO_APE_ATOLL),
	SPELL_WATER_WAVE(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.WATER_WAVE),
	SPELL_CHARGE_AIR_ORB(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.CHARGE_AIR_ORB),
	SPELL_VULNERABILITY(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.VULNERABILITY),
	SPELL_LVL_5_ENCHANT(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.LVL_5_ENCHANT),
	SPELL_TELEPORT_TO_KOUREND(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.TELEPORT_TO_KOUREND),
	SPELL_EARTH_WAVE(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.EARTH_WAVE),
	SPELL_ENFEEBLE(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.ENFEEBLE),
	SPELL_FIRE_WAVE(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.FIRE_WAVE),
	SPELL_ENTANGLE(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.ENTANGLE),
	SPELL_TELEOTHER_LUMBRIDGE(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.TELEOTHER_LUMBRIDGE),
	SPELL_STUN(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.STUN),
	SPELL_CHARGE(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.CHARGE),
	SPELL_WIND_SURGE(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.WIND_SURGE),
	SPELL_TELEOTHER_FALADOR(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.TELEOTHER_FALADOR),
	SPELL_WATER_SURGE(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.WATER_SURGE),
	SPELL_TELE_BLOCK(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.TELE_BLOCK),
	SPELL_LVL_6_ENCHANT(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.LVL_6_ENCHANT),
	SPELL_TELEOTHER_CAMELOT(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.TELEOTHER_CAMELOT),
	SPELL_EARTH_SURGE(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.EARTH_SURGE),
	SPELL_LVL_7_ENCHANT(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.LVL_7_ENCHANT),
	SPELL_FIRE_SURGE(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.FIRE_SURGE),
	SPELL_BOUNTY_TARGET_TELEPORT2(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.BOUNTY_TARGET_TELEPORT),
	/* END OF STANDARD SPELL BOOK WIDGETS*/
	
	/* ANCIENT SPELL BOOK WIDGETS*/
	SPELL_ICE_RUSH(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.ICE_RUSH),
	SPELL_ICE_BLITZ(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.ICE_BLITZ),
	SPELL_ICE_BURST(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.ICE_BURST),
	SPELL_ICE_BARRAGE(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.ICE_BARRAGE),
	SPELL_BLOOD_RUSH(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.BLOOD_RUSH),
	SPELL_BLOOD_BLITZ(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.BLOOD_BLITZ),
	SPELL_BLOOD_BURST(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.BLOOD_BURST),
	SPELL_BLOOD_BARRAGE(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.BLOOD_BARRAGE),
	SPELL_SMOKE_RUSH(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.SMOKE_RUSH),
	SPELL_SMOKE_BLITZ(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.SMOKE_BLITZ),
	SPELL_SMOKE_BURST(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.SMOKE_BURST),
	SPELL_SMOKE_BARRAGE(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.SMOKE_BARRAGE),
	SPELL_SHADOW_RUSH(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.SHADOW_RUSH),
	SPELL_SHADOW_BLITZ(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.SHADOW_BLITZ),
	SPELL_SHADOW_BURST(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.SHADOW_BURST),
	SPELL_SHADOW_BARRAGE(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.SHADOW_BARRAGE),
	SPELL_PADDEWWA_TELEPORT(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.PADDEWWA_TELEPORT),
	SPELL_SENNTISTEN_TELEPORT(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.SENNTISTEN_TELEPORT),
	SPELL_KHARYRLL_TELEPORT(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.KHARYRLL_TELEPORT),
	SPELL_LASSAR_TELEPORT(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.LASSAR_TELEPORT),
	SPELL_DAREEYAK_TELEPORT(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.DAREEYAK_TELEPORT),
	SPELL_CARRALLANGER_TELEPORT(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.CARRALLANGER_TELEPORT),
	SPELL_ANNAKARL_TELEPORT(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.ANNAKARL_TELEPORT),
	SPELL_GHORROCK_TELEPORT(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.GHORROCK_TELEPORT),
	SPELL_BOUNTY_TARGET_TELEPORT(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.BOUNTY_TARGET_TELEPORT),
	/* END OF ANCIENT SPELL BOOK WIDGETS*/
	
	/* LUNAR SPELL BOOK WIDGETS*/
	SPELL_VENGEANCE_OTHER(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.VENGEANCE_OTHER),
	SPELL_VENGEANCE(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.VENGEANCE),
	SPELL_BOUNTY_TARGET_TELEPORT3(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.BOUNTY_TARGET_TELEPORT),
	SPELL_BAKE_PIE(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.BAKE_PIE),
	SPELL_CURE_PLANT(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.CURE_PLANT),
	SPELL_MONSTER_EXAMINE(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.MONSTER_EXAMINE),
	SPELL_NPC_CONTACT(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.NPC_CONTACT),
	SPELL_CURE_OTHER(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.CURE_OTHER),
	SPELL_HUMIDIFY(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.HUMIDIFY),
	SPELL_MOONCLAN_TELEPORT(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.MOONCLAN_TELEPORT),
	SPELL_TELE_GROUP_MOONCLAN(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.TELE_GROUP_MOONCLAN),
	SPELL_CURE_ME(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.CURE_ME),
	SPELL_HUNTER_KIT(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.HUNTER_KIT),
	SPELL_WATERBIRTH_TELEPORT(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.WATERBIRTH_TELEPORT),
	SPELL_TELE_GROUP_WATERBIRTH(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.TELE_GROUP_WATERBIRTH),
	SPELL_CURE_GROUP(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.CURE_GROUP),
	SPELL_STAT_SPY(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.STAT_SPY),
	SPELL_BARBARIAN_TELEPORT(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.BARBARIAN_TELEPORT),
	SPELL_TELE_GROUP_BARBARIAN(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.TELE_GROUP_BARBARIAN),
	SPELL_SUPERGLASS_MAKE(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.SUPERGLASS_MAKE),
	SPELL_TAN_LEATHER(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.TAN_LEATHER),
	SPELL_KHAZARD_TELEPORT(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.KHAZARD_TELEPORT),
	SPELL_TELE_GROUP_KHAZARD(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.TELE_GROUP_KHAZARD),
	SPELL_DREAM(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.DREAM),
	SPELL_STRING_JEWELLERY(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.STRING_JEWELLERY),
	SPELL_STAT_RESTORE_POT_SHARE(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.STAT_RESTORE_POT_SHARE),
	SPELL_MAGIC_IMBUE(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.MAGIC_IMBUE),
	SPELL_FERTILE_SOIL(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.FERTILE_SOIL),
	SPELL_BOOST_POTION_SHARE(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.BOOST_POTION_SHARE),
	SPELL_FISHING_GUILD_TELEPORT(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.FISHING_GUILD_TELEPORT),
	SPELL_TELE_GROUP_FISHING_GUILD(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.TELE_GROUP_FISHING_GUILD),
	SPELL_PLANK_MAKE(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.PLANK_MAKE),
	SPELL_CATHERBY_TELEPORT(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.CATHERBY_TELEPORT),
	SPELL_TELE_GROUP_CATHERBY(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.TELE_GROUP_CATHERBY),
	SPELL_RECHARGE_DRAGONSTONE(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.RECHARGE_DRAGONSTONE),
	SPELL_ICE_PLATEAU_TELEPORT(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.ICE_PLATEAU_TELEPORT),
	SPELL_TELE_GROUP_ICE_PLATEAU(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.TELE_GROUP_ICE_PLATEAU),
	SPELL_ENERGY_TRANSFER(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.ENERGY_TRANSFER),
	SPELL_HEAL_OTHER(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.HEAL_OTHER),
	SPELL_HEAL_GROUP(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.HEAL_GROUP),
	SPELL_SPELLBOOK_SWAP(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.SPELLBOOK_SWAP),
	SPELL_GEOMANCY(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.GEOMANCY),
	SPELL_SPIN_FLAX(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.SPIN_FLAX),
	SPELL_OURANIA_TELEPORT(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.OURANIA_TELEPORT),
	/* END OF LUNAR SPELL BOOK WIDGETS*/
	SPELL_TOOLTIP(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.TOOLTIP),
	/* ARCEUUS SPELL BOOK WIDGETS*/
	SPELL_BASIC_REANIMATION(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.BASIC_REANIMATION),
	SPELL_ARCEUUS_LIBRARY_TELEPORT(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.ARCEUUS_LIBRARY_TELEPORT),
	SPELL_ADEPT_REANIMATION(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.ADEPT_REANIMATION),
	SPELL_EXPERT_REANIMATION(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.EXPERT_REANIMATION),
	SPELL_MASTER_REANIMATION(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.MASTER_REANIMATION),
	SPELL_DRAYNOR_MANOR_TELEPORT(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.DRAYNOR_MANOR_TELEPORT),
	SPELL_MIND_ALTAR_TELEPORT(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.MIND_ALTAR_TELEPORT),
	SPELL_RESPAWN_TELEPORT(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.RESPAWN_TELEPORT),
	SPELL_SALVE_GRAVEYARD_TELEPORT(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.SALVE_GRAVEYARD_TELEPORT),
	SPELL_FENKENSTRAINS_CASTLE_TELEPORT(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.FENKENSTRAINS_CASTLE_TELEPORT),
	SPELL_WEST_ARDOUGNE_TELEPORT(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.WEST_ARDOUGNE_TELEPORT),
	SPELL_HARMONY_ISLAND_TELEPORT(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.HARMONY_ISLAND_TELEPORT),
	SPELL_CEMETERY_TELEPORT(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.CEMETERY_TELEPORT),
	SPELL_RESURRECT_CROPS(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.RESURRECT_CROPS),
	SPELL_BARROWS_TELEPORT(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.BARROWS_TELEPORT),
	SPELL_APE_ATOLL_TELEPORT(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.APE_ATOLL_TELEPORT),
	SPELL_BATTLEFRONT_TELEPORT(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.BATTLEFRONT_TELEPORT),
	SPELL_INFERIOR_DEMONBANE(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.INFERIOR_DEMONBANE),
	SPELL_SUPERIOR_DEMONBANE(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.SUPERIOR_DEMONBANE),
	SPELL_DARK_DEMONBANE(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.DARK_DEMONBANE),
	SPELL_MARK_OF_DARKNESS(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.MARK_OF_DARKNESS),
	SPELL_GHOSTLY_GRASP(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.GHOSTLY_GRASP),
	SPELL_SKELETAL_GRASP(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.SKELETAL_GRASP),
	SPELL_UNDEAD_GRASP(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.UNDEAD_GRASP),
	SPELL_WARD_OF_ARCEUUS(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.WARD_OF_ARCEUUS),
	SPELL_LESSER_CORRUPTION(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.LESSER_CORRUPTION),
	SPELL_GREATER_CORRUPTION(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.GREATER_CORRUPTION),
	SPELL_DEMONIC_OFFERING(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.DEMONIC_OFFERING),
	SPELL_SINISTER_OFFERING(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.SINISTER_OFFERING),
	SPELL_DEGRIME(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.DEGRIME),
	SPELL_SHADOW_VEIL(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.SHADOW_VEIL),
	SPELL_VILE_VIGOUR(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.VILE_VIGOUR),
	SPELL_DARK_LURE(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.DARK_LURE),
	SPELL_DEATH_CHARGE(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.DEATH_CHARGE),
	SPELL_RESURRECT_LESSER_GHOST(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.RESURRECT_LESSER_GHOST),
	SPELL_RESURRECT_LESSER_SKELETON(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.RESURRECT_LESSER_SKELETON),
	SPELL_RESURRECT_LESSER_ZOMBIE(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.RESURRECT_LESSER_ZOMBIE),
	SPELL_RESURRECT_SUPERIOR_GHOST(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.RESURRECT_SUPERIOR_GHOST),
	SPELL_RESURRECT_SUPERIOR_SKELETON(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.RESURRECT_SUPERIOR_SKELETON),
	SPELL_RESURRECT_SUPERIOR_ZOMBIE(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.RESURRECT_SUPERIOR_ZOMBIE),
	SPELL_RESURRECT_GREATER_GHOST(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.RESURRECT_GREATER_GHOST),
	SPELL_RESURRECT_GREATER_SKELETON(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.RESURRECT_GREATER_SKELETON),
	SPELL_RESURRECT_GREATER_ZOMBIE(WidgetIDPlus.SPELLBOOK_GROUP_ID, WidgetIDPlus.SpellBook.RESURRECT_GREATER_ZOMBIE),
	/* END OF ARCEUUS SPELL BOOK WIDGETS*/
	
	MULTICOMBAT_RESIZEABLE(WidgetIDPlus.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDPlus.ResizableViewport.MULTICOMBAT_INDICATOR),
	
	MUSICTAB_INTERFACE(WidgetIDPlus.MUSICTAB_GROUP_ID, 1),
	MUSICTAB_SONG_BOX(WidgetIDPlus.MUSICTAB_GROUP_ID, 2),
	MUSICTAB_ALL_SONGS(WidgetIDPlus.MUSICTAB_GROUP_ID, 3),
	MUSICTAB_SCROLLBAR(WidgetIDPlus.MUSICTAB_GROUP_ID, 4),
	MUSICTAB_PLAYING(WidgetIDPlus.MUSICTAB_GROUP_ID, 5),
	MUSICTAB_CURRENT_SONG_NAME(WidgetIDPlus.MUSICTAB_GROUP_ID, 6),
	MUSICTAB_AUTO_BUTTON_LISTENER(WidgetIDPlus.MUSICTAB_GROUP_ID, 7),
	MUSICTAB_AUTO_BUTTON(WidgetIDPlus.MUSICTAB_GROUP_ID, 8),
	MUSICTAB_MANUAL_BUTTON_LISTENER(WidgetIDPlus.MUSICTAB_GROUP_ID, 9),
	MUSICTAB_MANUAL_BUTTON(WidgetIDPlus.MUSICTAB_GROUP_ID, 10),
	MUSICTAB_LOOP_BUTTON_LISTENER(WidgetIDPlus.MUSICTAB_GROUP_ID, 11),
	MUSICTAB_LOOP_BUTTON(WidgetIDPlus.MUSICTAB_GROUP_ID, 12),
	MUSICTAB_UNLOCKED_SONGS(WidgetIDPlus.MUSICTAB_GROUP_ID, 13),
	
	QUESTTAB_QUEST_TAB(WidgetIDPlus.QUESTTAB_GROUP_ID, WidgetIDPlus.QuestTab.QUEST_TAB),
	
	EQUIPMENT_MELEE_STRENGTH(WidgetIDPlus.EQUIPMENT_PAGE_GROUP_ID, WidgetIDPlus.EquipmentWidgetIdentifiers.MELEE_STRENGTH),
	EQUIPMENT_RANGED_STRENGTH(WidgetIDPlus.EQUIPMENT_PAGE_GROUP_ID, WidgetIDPlus.EquipmentWidgetIdentifiers.RANGED_STRENGTH),
	EQUIPMENT_MAGIC_DAMAGE(WidgetIDPlus.EQUIPMENT_PAGE_GROUP_ID, WidgetIDPlus.EquipmentWidgetIdentifiers.MAGIC_DAMAGE),
	EQUIP_YOUR_CHARACTER(WidgetIDPlus.EQUIPMENT_PAGE_GROUP_ID, WidgetIDPlus.EquipmentWidgetIdentifiers.EQUIP_YOUR_CHARACTER),
	
	BANK_PIN_TOP_LEFT_TEXT(WidgetIDPlus.BANK_PIN_GROUP_ID, WidgetIDPlus.BankPin.TOP_LEFT_TEXT),
	BANK_PIN_EXIT_BUTTON(WidgetIDPlus.BANK_PIN_GROUP_ID, WidgetIDPlus.BankPin.EXIT_BUTTON),
	BANK_PIN_FORGOT_BUTTON(WidgetIDPlus.BANK_PIN_GROUP_ID, WidgetIDPlus.BankPin.FORGOT_BUTTON),
	BANK_PIN_FIRST_ENTERED(WidgetIDPlus.BANK_PIN_GROUP_ID, WidgetIDPlus.BankPin.FIRST_ENTERED),
	BANK_PIN_SECOND_ENTERED(WidgetIDPlus.BANK_PIN_GROUP_ID, WidgetIDPlus.BankPin.SECOND_ENTERED),
	BANK_PIN_THIRD_ENTERED(WidgetIDPlus.BANK_PIN_GROUP_ID, WidgetIDPlus.BankPin.THIRD_ENTERED),
	BANK_PIN_FOURTH_ENTERED(WidgetIDPlus.BANK_PIN_GROUP_ID, WidgetIDPlus.BankPin.FOURTH_ENTERED),
	BANK_PIN_INSTRUCTION_TEXT(WidgetIDPlus.BANK_PIN_GROUP_ID, WidgetIDPlus.BankPin.INSTRUCTION_TEXT),
	BANK_PIN_1(WidgetIDPlus.BANK_PIN_GROUP_ID, WidgetIDPlus.BankPin.BUTTON_1),
	BANK_PIN_2(WidgetIDPlus.BANK_PIN_GROUP_ID, WidgetIDPlus.BankPin.BUTTON_2),
	BANK_PIN_3(WidgetIDPlus.BANK_PIN_GROUP_ID, WidgetIDPlus.BankPin.BUTTON_3),
	BANK_PIN_4(WidgetIDPlus.BANK_PIN_GROUP_ID, WidgetIDPlus.BankPin.BUTTON_4),
	BANK_PIN_5(WidgetIDPlus.BANK_PIN_GROUP_ID, WidgetIDPlus.BankPin.BUTTON_5),
	BANK_PIN_6(WidgetIDPlus.BANK_PIN_GROUP_ID, WidgetIDPlus.BankPin.BUTTON_6),
	BANK_PIN_7(WidgetIDPlus.BANK_PIN_GROUP_ID, WidgetIDPlus.BankPin.BUTTON_7),
	BANK_PIN_8(WidgetIDPlus.BANK_PIN_GROUP_ID, WidgetIDPlus.BankPin.BUTTON_8),
	BANK_PIN_9(WidgetIDPlus.BANK_PIN_GROUP_ID, WidgetIDPlus.BankPin.BUTTON_9),
	BANK_PIN_10(WidgetIDPlus.BANK_PIN_GROUP_ID, WidgetIDPlus.BankPin.BUTTON_10),
	
	JEWELLERY_BOX_DUEL_RING(WidgetIDPlus.JEWELLERY_BOX_GROUP_ID, WidgetIDPlus.JewelBox.DUEL_RING),
	JEWELLERY_BOX_GAME_NECK(WidgetIDPlus.JEWELLERY_BOX_GROUP_ID, WidgetIDPlus.JewelBox.GAME_NECK),
	JEWELLERY_BOX_COMB_BRAC(WidgetIDPlus.JEWELLERY_BOX_GROUP_ID, WidgetIDPlus.JewelBox.COMB_BRAC),
	JEWELLERY_BOX_SKIL_NECK(WidgetIDPlus.JEWELLERY_BOX_GROUP_ID, WidgetIDPlus.JewelBox.SKIL_NECK),
	JEWELLERY_BOX_RING_OFGP(WidgetIDPlus.JEWELLERY_BOX_GROUP_ID, WidgetIDPlus.JewelBox.RING_OFGP),
	JEWELLERY_BOX_AMUL_GLOR(WidgetIDPlus.JEWELLERY_BOX_GROUP_ID, WidgetIDPlus.JewelBox.AMUL_GLOR),
	OPTIONS_CAMERA_ZOOM_SLIDER_HANDLE(WidgetIDPlus.OPTIONS_GROUP_ID, WidgetIDPlus.Options.CAMERA_ZOOM_SLIDER_HANDLE),
	OPTIONS_MUSIC_SLIDER(WidgetIDPlus.OPTIONS_GROUP_ID, WidgetIDPlus.Options.MUSIC_SLIDER),
	OPTIONS_SOUND_EFFECT_SLIDER(WidgetIDPlus.OPTIONS_GROUP_ID, WidgetIDPlus.Options.SOUND_EFFECT_SLIDER),
	OPTIONS_AREA_SOUND_SLIDER(WidgetIDPlus.OPTIONS_GROUP_ID, WidgetIDPlus.Options.AREA_SOUND_SLIDER),
	
	TRADING_WITH(WidgetIDPlus.PLAYER_TRADE_SCREEN_GROUP_ID, WidgetIDPlus.TradeScreen.FIRST_TRADING_WITH),
	SECOND_TRADING_WITH(WidgetIDPlus.PLAYER_TRADE_CONFIRM_GROUP_ID, WidgetIDPlus.TradeScreen.SECOND_TRADING_WITH),
	SECOND_TRADING_WITH_ACCEPT_BUTTON(WidgetIDPlus.PLAYER_TRADE_CONFIRM_GROUP_ID, WidgetIDPlus.TradeScreen.SECOND_ACCEPT_FUNC),
	SECOND_TRADING_WITH_ACCEPT_TEXT(WidgetIDPlus.PLAYER_TRADE_CONFIRM_GROUP_ID, WidgetIDPlus.TradeScreen.SECOND_ACCEPT_TEXT),
	SECOND_TRADING_WITH_DECLINE_BUTTON(WidgetIDPlus.PLAYER_TRADE_CONFIRM_GROUP_ID, WidgetIDPlus.TradeScreen.SECOND_DECLINE_FUNC),
	SECOND_TRADING_WITH_DECLINE_TEXT(WidgetIDPlus.PLAYER_TRADE_CONFIRM_GROUP_ID, WidgetIDPlus.TradeScreen.SECOND_DECLINE_TEXT),
	SECOND_TRADING_WITH_MY_OFFER(WidgetIDPlus.PLAYER_TRADE_CONFIRM_GROUP_ID, WidgetIDPlus.TradeScreen.SECOND_MY_OFFER),
	SECOND_TRADING_WITH_THEIR_OFFER(WidgetIDPlus.PLAYER_TRADE_CONFIRM_GROUP_ID, WidgetIDPlus.TradeScreen.SECOND_THEIR_OFFER),
	SECOND_TRADING_WITH_MY_ITEMS(WidgetIDPlus.PLAYER_TRADE_CONFIRM_GROUP_ID, WidgetIDPlus.TradeScreen.SECOND_MY_ITEMS),
	SECOND_TRADING_WITH_THEIR_ITEMS(WidgetIDPlus.PLAYER_TRADE_CONFIRM_GROUP_ID, WidgetIDPlus.TradeScreen.SECOND_THEIR_ITEMS),
	
	GAUNTLET_MAP(WidgetIDPlus.GAUNTLET_MAP_GROUP_ID, WidgetIDPlus.GauntletMap.CONTAINER),
	
	SHOP_ITEMS_CONTAINER(WidgetIDPlus.SHOP_GROUP_ID, WidgetIDPlus.Shop.ITEMS_CONTAINER),
	
	POH_TREASURE_CHEST_INVENTORY_CONTAINER(WidgetIDPlus.POH_TREASURE_CHEST_INVENTORY_GROUP_ID, 0),
	
	TRADE_WINDOW_HEADER(WidgetIDPlus.TRADE_WINDOW_GROUP_ID, WidgetIDPlus.Trade.HEADER),
	
	TOA_PARTY_LAYER(WidgetIDPlus.TOA_PARTY_GROUP_ID, 2),
	TOA_RAID_LAYER(WidgetIDPlus.TOA_RAID_GROUP_ID, 3),
	;
	
	private final int groupId;
	private final int childId;
	
	WidgetInfoPlus(int groupId, int childId)
	{
		this.groupId = groupId;
		this.childId = childId;
	}
	
	/**
	 * Gets the ID of the group-child pairing.
	 *
	 * @return the ID
	 */
	public int getId()
	{
		return groupId << 16 | childId;
	}
	
	/**
	 * Gets the group ID of the pair.
	 *
	 * @return the group ID
	 */
	public int getGroupId()
	{
		return groupId;
	}
	
	/**
	 * Gets the ID of the child in the group.
	 *
	 * @return the child ID
	 */
	public int getChildId()
	{
		return childId;
	}
	
	/**
	 * Gets the packed widget ID.
	 *
	 * @return the packed ID
	 */
	public int getPackedId()
	{
		return groupId << 16 | childId;
	}
	
	/**
	 * Utility method that converts an ID returned by {@link #getId()} back
	 * to its group ID.
	 *
	 * @param id passed group-child ID
	 * @return the group ID
	 */
	public static int TO_GROUP(int id)
	{
		return id >>> 16;
	}
	
	/**
	 * Utility method that converts an ID returned by {@link #getId()} back
	 * to its child ID.
	 *
	 * @param id passed group-child ID
	 * @return the child ID
	 */
	public static int TO_CHILD(int id)
	{
		return id & 0xFFFF;
	}
	
	/**
	 * Packs the group and child IDs into a single integer.
	 *
	 * @param groupId the group ID
	 * @param childId the child ID
	 * @return the packed ID
	 */
	public static int PACK(int groupId, int childId)
	{
		return groupId << 16 | childId;
	}
	
}
